// Class __default
// Dafny class __default compiled into Java
package DynamoDbMiddlewareSupport_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static <__X, __Y> boolean NoMap(dafny.TypeDescriptor<__X> _td___X, dafny.TypeDescriptor<__Y> _td___Y, Wrappers_Compile.Option<dafny.DafnyMap<? extends __X, ? extends __Y>> m)
  {
    return ((m).is_None()) || ((((long) ((m).dtor_value()).cardinalityInt()) == 0 ? 0 : 1) == 0);
  }
  public static <__X> boolean NoList(dafny.TypeDescriptor<__X> _td___X, Wrappers_Compile.Option<dafny.DafnySequence<? extends __X>> m)
  {
    return ((m).is_None()) || ((((long) ((m).dtor_value()).cardinalityInt()) == 0 ? 0 : 1) == 0);
  }
  public static Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> IsWriteable(DdbMiddlewareConfig_Compile.TableConfig config, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item)
  {
    Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> ret = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
    Wrappers_Compile.Result<Boolean, dafny.DafnySequence<? extends Character>> _0_is__writable;
    Wrappers_Compile.Result<Boolean, dafny.DafnySequence<? extends Character>> _out0;
    _out0 = DynamoDBSupport_Compile.__default.IsWriteable(item);
    _0_is__writable = _out0;
    ret = (_0_is__writable).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.TypeDescriptor.BOOLEAN, dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      dafny.DafnySequence<? extends Character> _1_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_1_e_boxed0));
      return DdbMiddlewareConfig_Compile.__default.E(_1_e);
    }));
    return ret;
  }
  public static boolean IsSigned(DdbMiddlewareConfig_Compile.TableConfig config, dafny.DafnySequence<? extends Character> attr)
  {
    return DynamoDBSupport_Compile.__default.IsSigned((((config).dtor_itemEncryptor()).config()).dtor_attributeActionsOnEncrypt(), attr);
  }
  public static Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> TestConditionExpression(DdbMiddlewareConfig_Compile.TableConfig config, Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> expr, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>> attrNames, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>> attrValues)
  {
    return (DynamoDBSupport_Compile.__default.TestConditionExpression((((config).dtor_itemEncryptor()).config()).dtor_attributeActionsOnEncrypt(), expr, attrNames, attrValues)).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.TypeDescriptor.BOOLEAN, dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_0_e_boxed0) -> {
      dafny.DafnySequence<? extends Character> _0_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_0_e_boxed0));
      return DdbMiddlewareConfig_Compile.__default.E(_0_e);
    }));
  }
  public static Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> TestUpdateExpression(DdbMiddlewareConfig_Compile.TableConfig config, Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> expr, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>> attrNames, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>> attrValues)
  {
    return (DynamoDBSupport_Compile.__default.TestUpdateExpression((((config).dtor_itemEncryptor()).config()).dtor_attributeActionsOnEncrypt(), expr, attrNames, attrValues)).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.TypeDescriptor.BOOLEAN, dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_0_e_boxed0) -> {
      dafny.DafnySequence<? extends Character> _0_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_0_e_boxed0));
      return DdbMiddlewareConfig_Compile.__default.E(_0_e);
    }));
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> AddSignedBeacons(DdbMiddlewareConfig_Compile.TableConfig config, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> empty());
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.AddSignedBeacons((config).dtor_search(), item);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> GetEncryptedBeacons(DdbMiddlewareConfig_Compile.TableConfig config, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item, DynamoDbEncryptionUtil_Compile.MaybeKeyId keyId)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> empty());
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.GetEncryptedBeacons((config).dtor_search(), item, keyId);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<DynamoDbEncryptionUtil_Compile.MaybeKeyId, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> GetBeaconKeyId(DdbMiddlewareConfig_Compile.TableConfig config, Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> keyExpr, Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> filterExpr, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>> values, Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>> names)
  {
    return (DynamoDBSupport_Compile.__default.GetBeaconKeyId((config).dtor_search(), keyExpr, filterExpr, values, names)).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(DynamoDbEncryptionUtil_Compile.MaybeKeyId._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_0_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _0_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_0_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_0_e);
    }));
  }
  public static Wrappers_Compile.Result<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> GetKeyIdFromHeader(DdbMiddlewareConfig_Compile.TableConfig config, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput output)
  {
    if ((((config).dtor_search()).is_Some()) && (((((((config).dtor_search()).dtor_value()).curr()).dtor_keySource()).dtor_keyLoc()).is_MultiLoc())) {
      Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((output).dtor_parsedHeader()).is_Some(), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("In multi-tenant mode, the parsed header is required.")));
      if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
        return (_0_valueOrError0).<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
      } else {
        dafny.DafnySequence<? extends software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey> _1_keys = (((output).dtor_parsedHeader()).dtor_value()).dtor_encryptedDataKeys();
        Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _2_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((long) (_1_keys).cardinalityInt()) == ((long) 1L), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("Encrypt header has more than one Encrypted Data Key")));
        if ((_2_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          return (_2_valueOrError1).<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
        } else {
          Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _3_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((((software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey)(java.lang.Object)((_1_keys).select(0)))).dtor_keyProviderId()).equals(__default.HierarchicalKeyringId()), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("In multi-tenant mode, keyProviderId must be aws-kms-hierarchy")));
          if ((_3_valueOrError2).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
            return (_3_valueOrError2).<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
          } else {
            Wrappers_Compile.Result<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _4_valueOrError3 = (UTF8.__default.Decode((((software.amazon.cryptography.materialproviders.internaldafny.types.EncryptedDataKey)(java.lang.Object)((_1_keys).select(0)))).dtor_keyProviderInfo())).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_5_e_boxed0) -> {
              dafny.DafnySequence<? extends Character> _5_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_5_e_boxed0));
              return DdbMiddlewareConfig_Compile.__default.E(_5_e);
            }));
            if ((_4_valueOrError3).IsFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
              return (_4_valueOrError3).<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>>PropagateFailure(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
            } else {
              dafny.DafnySequence<? extends Character> _6_keyId = (_4_valueOrError3).Extract(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
              return Wrappers_Compile.Result.<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_Some(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), _6_keyId));
            }
          }
        }
      }
    } else {
      return Wrappers_Compile.Result.<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
    }
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> RemoveBeacons(DdbMiddlewareConfig_Compile.TableConfig config, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item)
  {
    return (DynamoDBSupport_Compile.__default.RemoveBeacons((config).dtor_search(), item)).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_0_e_boxed0) -> {
      dafny.DafnySequence<? extends Character> _0_e = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)(_0_e_boxed0));
      return DdbMiddlewareConfig_Compile.__default.E(_0_e);
    }));
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> QueryInputForBeacons(DdbMiddlewareConfig_Compile.TableConfig config, software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput req)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.QueryInputForBeacons((config).dtor_search(), (((config).dtor_itemEncryptor()).config()).dtor_attributeActionsOnEncrypt(), req);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> QueryOutputForBeacons(DdbMiddlewareConfig_Compile.TableConfig config, software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryInput req, software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput resp)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.QueryOutputForBeacons((config).dtor_search(), req, resp);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.QueryOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> ScanInputForBeacons(DdbMiddlewareConfig_Compile.TableConfig config, software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput req)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.ScanInputForBeacons((config).dtor_search(), (((config).dtor_itemEncryptor()).config()).dtor_attributeActionsOnEncrypt(), req);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> ScanOutputForBeacons(DdbMiddlewareConfig_Compile.TableConfig config, software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanInput req, software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput resp)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.ScanOutputForBeacons((config).dtor_search(), req, resp);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(software.amazon.cryptography.services.dynamodb.internaldafny.types.ScanOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> GetVirtualFields(SearchableEncryptionInfo_Compile.SearchInfo search, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item, Wrappers_Compile.Option<java.lang.Integer> version)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,dafny.DafnySequence<? extends Character>> empty());
    if (((version).is_Some()) && (((version).dtor_value()) != (1))) {
      output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Failure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("Beacon Version Number must be '1'")));
      return output;
    }
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.GetVirtualFields((search).curr(), item);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> GetCompoundBeacons(SearchableEncryptionInfo_Compile.SearchInfo search, dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item, Wrappers_Compile.Option<java.lang.Integer> version)
  {
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,dafny.DafnySequence<? extends Character>> empty());
    if (((version).is_Some()) && (((version).dtor_value()) != (1))) {
      output = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Failure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("Beacon Version Number must be '1'")));
      return output;
    }
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _0_ret;
    Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error> _out0;
    _out0 = DynamoDBSupport_Compile.__default.GetCompoundBeacons((search).curr(), item);
    _0_ret = _out0;
    output = (_0_ret).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>MapFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error _1_e = ((software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(_1_e);
    }));
    return output;
  }
  public static dafny.DafnySequence<? extends java.lang.Byte> HierarchicalKeyringId()
  {
    dafny.DafnySequence<? extends java.lang.Byte> _0_s = dafny.DafnySequence.<java.lang.Byte> of((byte) 97, (byte) 119, (byte) 115, (byte) 45, (byte) 107, (byte) 109, (byte) 115, (byte) 45, (byte) 104, (byte) 105, (byte) 101, (byte) 114, (byte) 97, (byte) 114, (byte) 99, (byte) 104, (byte) 121);
    return _0_s;
  }
  @Override
  public java.lang.String toString() {
    return "DynamoDbMiddlewareSupport._default";
  }
}
