// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographymaterialproviderssmithygenerated

import (
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/AwsCryptographyMaterialProvidersTypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/awscryptographymaterialproviderssmithygeneratedtypes"
)

type CryptographicMaterialsCache struct {
	Impl AwsCryptographyMaterialProvidersTypes.ICryptographicMaterialsCache
}

func (this *CryptographicMaterialsCache) PutCacheEntry(params awscryptographymaterialproviderssmithygeneratedtypes.PutCacheEntryInput) error {
	var dafny_request AwsCryptographyMaterialProvidersTypes.PutCacheEntryInput = PutCacheEntryInput_ToDafny(params)
	var dafny_response = this.Impl.PutCacheEntry(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyMaterialProvidersTypes.Error)
		return Error_FromDafny(err)
	}
	return nil
}

func (this *CryptographicMaterialsCache) GetCacheEntry(params awscryptographymaterialproviderssmithygeneratedtypes.GetCacheEntryInput) (*awscryptographymaterialproviderssmithygeneratedtypes.GetCacheEntryOutput, error) {
	var dafny_request AwsCryptographyMaterialProvidersTypes.GetCacheEntryInput = GetCacheEntryInput_ToDafny(params)
	var dafny_response = this.Impl.GetCacheEntry(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyMaterialProvidersTypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetCacheEntryOutput_FromDafny(dafny_response.Dtor_value().(AwsCryptographyMaterialProvidersTypes.GetCacheEntryOutput))
	return &native_response, nil

}

func (this *CryptographicMaterialsCache) UpdateUsageMetadata(params awscryptographymaterialproviderssmithygeneratedtypes.UpdateUsageMetadataInput) error {
	var dafny_request AwsCryptographyMaterialProvidersTypes.UpdateUsageMetadataInput = UpdateUsageMetadataInput_ToDafny(params)
	var dafny_response = this.Impl.UpdateUsageMetadata(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyMaterialProvidersTypes.Error)
		return Error_FromDafny(err)
	}
	return nil
}

func (this *CryptographicMaterialsCache) DeleteCacheEntry(params awscryptographymaterialproviderssmithygeneratedtypes.DeleteCacheEntryInput) error {
	var dafny_request AwsCryptographyMaterialProvidersTypes.DeleteCacheEntryInput = DeleteCacheEntryInput_ToDafny(params)
	var dafny_response = this.Impl.DeleteCacheEntry(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyMaterialProvidersTypes.Error)
		return Error_FromDafny(err)
	}
	return nil
}
