// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographymaterialproviderssmithygenerated

import (
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/AwsCryptographyMaterialProvidersTypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/awscryptographymaterialproviderssmithygeneratedtypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
)

type CryptographicMaterialsManagerNativeWrapper struct {
	AwsCryptographyMaterialProvidersTypes.ICryptographicMaterialsManager
	Impl awscryptographymaterialproviderssmithygeneratedtypes.ICryptographicMaterialsManager
}

func (this *CryptographicMaterialsManagerNativeWrapper) GetEncryptionMaterials(input AwsCryptographyMaterialProvidersTypes.GetEncryptionMaterialsInput) Wrappers.Result {
	var native_request = GetEncryptionMaterialsInput_FromDafny(input)
	var native_response, native_error = this.Impl.GetEncryptionMaterials(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(GetEncryptionMaterialsOutput_ToDafny(*native_response))
}

func (this *CryptographicMaterialsManagerNativeWrapper) DecryptMaterials(input AwsCryptographyMaterialProvidersTypes.DecryptMaterialsInput) Wrappers.Result {
	var native_request = DecryptMaterialsInput_FromDafny(input)
	var native_response, native_error = this.Impl.DecryptMaterials(native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(DecryptMaterialsOutput_ToDafny(*native_response))
}
