// Class __default
// Dafny class __default compiled into Java
package StructuredEncryptionCrypt_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> FieldKey(dafny.DafnySequence<? extends java.lang.Byte> HKDFOutput, int offset)
  {
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), java.lang.Integer.compareUnsigned(offset, __default.ONE__THIRD__MAX__INT()) < 0, StructuredEncryptionUtil_Compile.__default.E(dafny.DafnySequence.asString("Too many encrypted fields.")));
    if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      return (_0_valueOrError0).<dafny.DafnySequence<? extends java.lang.Byte>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()));
    } else {
      Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _1_keyR = AesKdfCtr.__default.AesKdfCtrStream(__default.FieldKeyNonce((int) ((offset) * (3))), HKDFOutput, ((int) ((long) (long) ((StructuredEncryptionUtil_Compile.__default.KeySize64()) + (StructuredEncryptionUtil_Compile.__default.NonceSize64())))));
      return (_1_keyR).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.primitives.internaldafny.types.OpaqueError._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.primitives.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)(_2_e_boxed0) -> {
        software.amazon.cryptography.primitives.internaldafny.types.Error _2_e = ((software.amazon.cryptography.primitives.internaldafny.types.Error)(java.lang.Object)(_2_e_boxed0));
        return software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error.create_AwsCryptographyPrimitives(_2_e);
      }));
    }
  }
  public static dafny.DafnySequence<? extends java.lang.Byte> FieldKeyNonce(int offset) {
    return dafny.DafnySequence.<java.lang.Byte>concatenate(dafny.DafnySequence.<java.lang.Byte>concatenate(__default.AwsDbeField(), dafny.DafnySequence.<java.lang.Byte> of(((byte) ((long) (long) ((StructuredEncryptionUtil_Compile.__default.KeySize64()) + (StructuredEncryptionUtil_Compile.__default.NonceSize64())))))), StandardLibrary_mUInt_Compile.__default.UInt32ToSeq(offset));
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> GetCommitKey(software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> key, dafny.DafnySequence<? extends java.lang.Byte> msgID)
  {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = (Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _0_commitKey;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _out0;
    _out0 = (client).Hkdf(software.amazon.cryptography.primitives.internaldafny.types.HkdfInput.create((((alg).dtor_commitment()).dtor_HKDF()).dtor_hmac(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends java.lang.Byte>>create_None(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor())), key, dafny.DafnySequence.<java.lang.Byte>concatenate(__default.LABEL__COMMITMENT__KEY(), msgID), (((alg).dtor_commitment()).dtor_HKDF()).dtor_outputKeyLength()));
    _0_commitKey = _out0;
    ret = (_0_commitKey).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.primitives.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.primitives.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)(_1_e_boxed0) -> {
      software.amazon.cryptography.primitives.internaldafny.types.Error _1_e = ((software.amazon.cryptography.primitives.internaldafny.types.Error)(java.lang.Object)(_1_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error.create_AwsCryptographyPrimitives(_1_e);
    }));
    return ret;
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> Encrypt(software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> key, StructuredEncryptionHeader_Compile.PartialHeader head, dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> data)
  {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out0;
    _out0 = __default.Crypt(Canonize_Compile.EncryptionSelector.create_DoEncrypt(), client, alg, key, head, data);
    _0_valueOrError0 = _out0;
    if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_0_valueOrError0).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
      return ret;
    }
    dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> _1_result;
    _1_result = (_0_valueOrError0).Extract(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), _1_result);
    return ret;
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> Decrypt(software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> key, StructuredEncryptionHeader_Compile.PartialHeader head, dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> data)
  {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out0;
    _out0 = __default.Crypt(Canonize_Compile.EncryptionSelector.create_DoDecrypt(), client, alg, key, head, data);
    _0_valueOrError0 = _out0;
    if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_0_valueOrError0).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
      return ret;
    }
    dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> _1_result;
    _1_result = (_0_valueOrError0).Extract(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), _1_result);
    return ret;
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> Crypt(Canonize_Compile.EncryptionSelector mode, software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> key, StructuredEncryptionHeader_Compile.PartialHeader head, dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> data)
  {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _0_fieldRootKeyR;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _out0;
    _out0 = (client).Hkdf(software.amazon.cryptography.primitives.internaldafny.types.HkdfInput.create((((alg).dtor_kdf()).dtor_HKDF()).dtor_hmac(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends java.lang.Byte>>create_None(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor())), key, dafny.DafnySequence.<java.lang.Byte>concatenate(__default.LABEL__ENCRYPTION__KEY(), (head).dtor_msgID()), (((alg).dtor_kdf()).dtor_HKDF()).dtor_outputKeyLength()));
    _0_fieldRootKeyR = _out0;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _1_valueOrError0 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte> empty(BoundedInts_Compile.uint8._typeDescriptor()));
    _1_valueOrError0 = (_0_fieldRootKeyR).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.primitives.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.primitives.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)(_2_e_boxed0) -> {
      software.amazon.cryptography.primitives.internaldafny.types.Error _2_e = ((software.amazon.cryptography.primitives.internaldafny.types.Error)(java.lang.Object)(_2_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error.create_AwsCryptographyPrimitives(_2_e);
    }));
    if ((_1_valueOrError0).IsFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_1_valueOrError0).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
      return ret;
    }
    dafny.DafnySequence<? extends java.lang.Byte> _3_fieldRootKey;
    _3_fieldRootKey = (_1_valueOrError0).Extract(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _4_valueOrError1 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out1;
    _out1 = __default.CryptList(mode, client, alg, _3_fieldRootKey, data);
    _4_valueOrError1 = _out1;
    if ((_4_valueOrError1).IsFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_4_valueOrError1).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
      return ret;
    }
    dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> _5_result;
    _5_result = (_4_valueOrError1).Extract(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), _5_result);
    return ret;
  }
  public static Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> CryptList(Canonize_Compile.EncryptionSelector mode, software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> fieldRootKey, dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> data)
  {
    Wrappers_Compile.Result<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
    dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem> _0_result;
    _0_result = dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> empty(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor());
    int _1_pos;
    _1_pos = 0;
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _2_valueOrError0 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    _2_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), java.lang.Long.compareUnsigned((long) (data).cardinalityInt(), (StandardLibrary_mUInt_Compile.__default.UINT32__LIMIT()).longValue()) < 0, StructuredEncryptionUtil_Compile.__default.E(dafny.DafnySequence.asString("Too many fields.")));
    if ((_2_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_2_valueOrError0).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
      return ret;
    }
    long _hi0 = (long) (data).cardinalityInt();
    for (long _3_i = (long) 0L; java.lang.Long.compareUnsigned(_3_i, _hi0) < 0; _3_i++) {
      if (java.util.Objects.equals((((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))).dtor_action(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction.create_ENCRYPT__AND__SIGN())) {
        software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal _4_newTerminal = (software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal)null;
        if (java.util.Objects.equals(mode, Canonize_Compile.EncryptionSelector.create_DoEncrypt())) {
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _5_valueOrError1 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out0;
          _out0 = __default.EncryptTerminal(client, alg, fieldRootKey, _1_pos, (((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))).dtor_key(), (((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))).dtor_data());
          _5_valueOrError1 = _out0;
          if ((_5_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
            ret = (_5_valueOrError1).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
            return ret;
          }
          _4_newTerminal = (_5_valueOrError1).Extract(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
        } else {
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _6_valueOrError2 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)null;
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out1;
          _out1 = __default.DecryptTerminal(client, alg, fieldRootKey, _1_pos, (((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))).dtor_key(), (((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))).dtor_data());
          _6_valueOrError2 = _out1;
          if ((_6_valueOrError2).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
            ret = (_6_valueOrError2).<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()));
            return ret;
          }
          _4_newTerminal = (_6_valueOrError2).Extract(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
        }
        _1_pos = (int) ((_1_pos) + (1));
        StructuredEncryptionUtil_Compile.CanonCryptoItem _7_newItem;
        StructuredEncryptionUtil_Compile.CanonCryptoItem _8_dt__update__tmp_h0 = ((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))));
        software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal _9_dt__update_hdata_h0 = _4_newTerminal;
        _7_newItem = StructuredEncryptionUtil_Compile.CanonCryptoItem.create((_8_dt__update__tmp_h0).dtor_key(), (_8_dt__update__tmp_h0).dtor_origKey(), _9_dt__update_hdata_h0, (_8_dt__update__tmp_h0).dtor_action());
        _0_result = dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>concatenate(_0_result, dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> of(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor(), _7_newItem));
      } else {
        _0_result = dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>concatenate(_0_result, dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem> of(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor(), ((StructuredEncryptionUtil_Compile.CanonCryptoItem)(java.lang.Object)((data).select(dafny.Helpers.unsignedToInt(_3_i))))));
      }
    }
    ret = Wrappers_Compile.Result.<dafny.DafnySequence<? extends StructuredEncryptionUtil_Compile.CanonCryptoItem>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(dafny.DafnySequence.<StructuredEncryptionUtil_Compile.CanonCryptoItem>_typeDescriptor(StructuredEncryptionUtil_Compile.CanonCryptoItem._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), _0_result);
    return ret;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> EncryptTerminal(software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> fieldRootKey, int offset, dafny.DafnySequence<? extends java.lang.Byte> path, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal data)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte> empty(BoundedInts_Compile.uint8._typeDescriptor()));
    _0_valueOrError0 = __default.FieldKey(fieldRootKey, offset);
    if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_0_valueOrError0).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    dafny.DafnySequence<? extends java.lang.Byte> _1_fieldKey;
    _1_fieldKey = (_0_valueOrError0).Extract(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    dafny.DafnySequence<? extends java.lang.Byte> _2_cipherkey;
    _2_cipherkey = (_1_fieldKey).take(StructuredEncryptionUtil_Compile.__default.KeySize64());
    dafny.DafnySequence<? extends java.lang.Byte> _3_nonce;
    _3_nonce = (_1_fieldKey).drop(StructuredEncryptionUtil_Compile.__default.KeySize64());
    dafny.DafnySequence<? extends java.lang.Byte> _4_value;
    _4_value = (data).dtor_value();
    software.amazon.cryptography.primitives.internaldafny.types.AESEncryptInput _5_encInput;
    _5_encInput = software.amazon.cryptography.primitives.internaldafny.types.AESEncryptInput.create(((alg).dtor_encrypt()).dtor_AES__GCM(), _3_nonce, _2_cipherkey, _4_value, path);
    Wrappers_Compile.Result<software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput, software.amazon.cryptography.primitives.internaldafny.types.Error> _6_encOutR;
    Wrappers_Compile.Result<software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput, software.amazon.cryptography.primitives.internaldafny.types.Error> _out0;
    _out0 = (client).AESEncrypt(_5_encInput);
    _6_encOutR = _out0;
    Wrappers_Compile.Result<software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _7_valueOrError1 = Wrappers_Compile.Result.<software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput.Default());
    _7_valueOrError1 = (_6_encOutR).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>MapFailure(software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput._typeDescriptor(), software.amazon.cryptography.primitives.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.primitives.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)(_8_e_boxed0) -> {
      software.amazon.cryptography.primitives.internaldafny.types.Error _8_e = ((software.amazon.cryptography.primitives.internaldafny.types.Error)(java.lang.Object)(_8_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error.create_AwsCryptographyPrimitives(_8_e);
    }));
    if ((_7_valueOrError1).IsFailure(software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_7_valueOrError1).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput _9_encOut;
    _9_encOut = (_7_valueOrError1).Extract(software.amazon.cryptography.primitives.internaldafny.types.AESEncryptOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _10_valueOrError2 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    _10_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((long) ((_9_encOut).dtor_authTag()).cardinalityInt()) == (StructuredEncryptionUtil_Compile.__default.AuthTagSize64()), StructuredEncryptionUtil_Compile.__default.E(dafny.DafnySequence.asString("Auth Tag Wrong Size.")));
    if ((_10_valueOrError2).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_10_valueOrError2).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    ret = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), StructuredEncryptionUtil_Compile.__default.ValueToData(dafny.DafnySequence.<java.lang.Byte>concatenate(dafny.DafnySequence.<java.lang.Byte>concatenate((data).dtor_typeId(), (_9_encOut).dtor_cipherText()), (_9_encOut).dtor_authTag()), StructuredEncryptionUtil_Compile.__default.BYTES__TYPE__ID()));
    return ret;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> DecryptTerminal(software.amazon.cryptography.primitives.internaldafny.AtomicPrimitivesClient client, software.amazon.cryptography.materialproviders.internaldafny.types.AlgorithmSuiteInfo alg, dafny.DafnySequence<? extends java.lang.Byte> fieldRootKey, int offset, dafny.DafnySequence<? extends java.lang.Byte> path, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal data)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> ret = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte> empty(BoundedInts_Compile.uint8._typeDescriptor()));
    _0_valueOrError0 = __default.FieldKey(fieldRootKey, offset);
    if ((_0_valueOrError0).IsFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_0_valueOrError0).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    dafny.DafnySequence<? extends java.lang.Byte> _1_dataKey;
    _1_dataKey = (_0_valueOrError0).Extract(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    dafny.DafnySequence<? extends java.lang.Byte> _2_encryptionKey;
    _2_encryptionKey = (_1_dataKey).take(StructuredEncryptionUtil_Compile.__default.KeySize64());
    dafny.DafnySequence<? extends java.lang.Byte> _3_nonce;
    _3_nonce = (_1_dataKey).drop(StructuredEncryptionUtil_Compile.__default.KeySize64());
    dafny.DafnySequence<? extends java.lang.Byte> _4_value;
    _4_value = (data).dtor_value();
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _5_valueOrError1 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    _5_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), java.lang.Long.compareUnsigned((long) (long) ((StructuredEncryptionUtil_Compile.__default.AuthTagSize64()) + ((long) 2L)), (long) (_4_value).cardinalityInt()) <= 0, StructuredEncryptionUtil_Compile.__default.E(dafny.DafnySequence.asString("cipherTxt too short.")));
    if ((_5_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_5_valueOrError1).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    software.amazon.cryptography.primitives.internaldafny.types.AESDecryptInput _6_decInput;
    _6_decInput = software.amazon.cryptography.primitives.internaldafny.types.AESDecryptInput.create(((alg).dtor_encrypt()).dtor_AES__GCM(), _2_encryptionKey, (_4_value).subsequence(dafny.Helpers.unsignedToInt(StructuredEncryptionUtil_Compile.__default.TYPEID__LEN64()), dafny.Helpers.unsignedToInt((long) (long) (((long) (_4_value).cardinalityInt()) - (StructuredEncryptionUtil_Compile.__default.AuthTagSize64())))), (_4_value).drop((long) (long) (((long) (_4_value).cardinalityInt()) - (StructuredEncryptionUtil_Compile.__default.AuthTagSize64()))), _3_nonce, path);
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _7_decOutR;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.primitives.internaldafny.types.Error> _out0;
    _out0 = (client).AESDecrypt(_6_decInput);
    _7_decOutR = _out0;
    Wrappers_Compile.Result<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _8_valueOrError2 = Wrappers_Compile.Result.<dafny.DafnySequence<? extends java.lang.Byte>, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>Default(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), dafny.DafnySequence.<java.lang.Byte> empty(BoundedInts_Compile.uint8._typeDescriptor()));
    _8_valueOrError2 = (_7_decOutR).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>MapFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.primitives.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.primitives.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>)(_9_e_boxed0) -> {
      software.amazon.cryptography.primitives.internaldafny.types.Error _9_e = ((software.amazon.cryptography.primitives.internaldafny.types.Error)(java.lang.Object)(_9_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error.create_AwsCryptographyPrimitives(_9_e);
    }));
    if ((_8_valueOrError2).IsFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor())) {
      ret = (_8_valueOrError2).<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal>PropagateFailure(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor());
      return ret;
    }
    dafny.DafnySequence<? extends java.lang.Byte> _10_decOut;
    _10_decOut = (_8_valueOrError2).Extract(dafny.DafnySequence.<java.lang.Byte>_typeDescriptor(BoundedInts_Compile.uint8._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor());
    ret = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.StructuredDataTerminal._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), StructuredEncryptionUtil_Compile.__default.ValueToData(_10_decOut, (_4_value).take(StructuredEncryptionUtil_Compile.__default.TYPEID__LEN64())));
    return ret;
  }
  public static int ONE__THIRD__MAX__INT()
  {
    return 1431655765;
  }
  public static dafny.DafnySequence<? extends java.lang.Byte> AwsDbeField()
  {
    dafny.DafnySequence<? extends java.lang.Byte> _0_s = dafny.DafnySequence.<java.lang.Byte> of((byte) 65, (byte) 119, (byte) 115, (byte) 68, (byte) 98, (byte) 101, (byte) 70, (byte) 105, (byte) 101, (byte) 108, (byte) 100);
    return _0_s;
  }
  public static dafny.DafnySequence<? extends java.lang.Byte> LABEL__COMMITMENT__KEY()
  {
    dafny.DafnySequence<? extends java.lang.Byte> _0_s = dafny.DafnySequence.<java.lang.Byte> of((byte) 65, (byte) 87, (byte) 83, (byte) 95, (byte) 68, (byte) 66, (byte) 69, (byte) 95, (byte) 67, (byte) 79, (byte) 77, (byte) 77, (byte) 73, (byte) 84, (byte) 95, (byte) 75, (byte) 69, (byte) 89);
    return _0_s;
  }
  public static dafny.DafnySequence<? extends java.lang.Byte> LABEL__ENCRYPTION__KEY()
  {
    dafny.DafnySequence<? extends java.lang.Byte> _0_s = dafny.DafnySequence.<java.lang.Byte> of((byte) 65, (byte) 87, (byte) 83, (byte) 95, (byte) 68, (byte) 66, (byte) 69, (byte) 95, (byte) 68, (byte) 69, (byte) 82, (byte) 73, (byte) 86, (byte) 69, (byte) 95, (byte) 75, (byte) 69, (byte) 89);
    return _0_s;
  }
  @Override
  public java.lang.String toString() {
    return "StructuredEncryptionCrypt._default";
  }
}
