// Class __default
// Dafny class __default compiled into Java
package TestUpdateExpr_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static <__T> void expect__equal(dafny.TypeDescriptor<__T> _td___T, __T a, __T b)
  {
    if (!java.util.Objects.equals(a, b)) {
      System.out.print((dafny.DafnySequence.asString("Not equal: ")).verbatimString());
      System.out.print(java.lang.String.valueOf(a));
      System.out.print((dafny.DafnySequence.asString(", ")).verbatimString());
      System.out.print(java.lang.String.valueOf(b));
      System.out.print((dafny.DafnySequence.asString("\n")).verbatimString());
    }
    if (!(java.util.Objects.equals(a, b))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryption/test/UpdateExpr.dfy(16,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
  }
  public static void TestExamples()
  {
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET ProductCategory = :c, Price = :p")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("ProductCategory"), dafny.DafnySequence.asString("Price")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET RelatedItems[1] = :ri")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("RelatedItems")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET #pr.#5star[1] = :r5, #pr.#3star = :r3")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("#pr"), dafny.DafnySequence.asString("#pr")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET Price = Price - :p")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("Price"), dafny.DafnySequence.asString("Price")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET #ri = list_append(#ri, :vals)")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("#ri"), dafny.DafnySequence.asString("#ri")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET #ri = list_append(:vals, #ri)")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("#ri"), dafny.DafnySequence.asString("#ri")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("SET Price = if_not_exists(Price, :p)")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("Price"), dafny.DafnySequence.asString("Price")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("REMOVE Brand, InStock, QuantityOnHand")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("Brand"), dafny.DafnySequence.asString("InStock"), dafny.DafnySequence.asString("QuantityOnHand")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("REMOVE RelatedItems[1], RelatedItems[2]")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("RelatedItems"), dafny.DafnySequence.asString("RelatedItems")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("ADD QuantityOnHand :q")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("QuantityOnHand")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttrs(dafny.DafnySequence.asString("DELETE Color :p")), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("Color")));
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>> _0_m;
    _0_m = dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("#pr"), dafny.DafnySequence.asString("foo")));
    __default.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>expect__equal(dafny.DafnySequence.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), DynamoDbUpdateExpr_Compile.__default.ExtractAttributes(dafny.DafnySequence.asString("SET #pr.#5star[1] = :r5, #pr.#3star = :r3"), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_Some(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor()), _0_m)), dafny.DafnySequence.<dafny.DafnySequence<? extends Character>> of(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), dafny.DafnySequence.asString("foo"), dafny.DafnySequence.asString("foo")));
  }
  @Override
  public java.lang.String toString() {
    return "TestUpdateExpr._default";
  }
}
