version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directories:
      - "*/runtimes/java"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "nuget"
    directories:
      - "*/runtimes/net"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "cargo"
    directories:
      - "*/runtimes/rust"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
