// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbtransformssmithygeneratedtypes

import (
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	dynamodbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

type GetNumberOfQueriesOutput struct {
	NumberOfQueries int32
}

func (input GetNumberOfQueriesOutput) Validate() error {
	if input.NumberOfQueries < 1 {
		return fmt.Errorf("PartitionCount has a minimum of 1 but has the value of %d.", input.NumberOfQueries)
	}
	if input.NumberOfQueries > 255 {
		return fmt.Errorf("PartitionCount has a maximum of 255 but has the value of %d.", input.NumberOfQueries)
	}

	return nil
}

type ResolveAttributesOutput struct {
	CompoundBeacons map[string]string

	VirtualFields map[string]string
}

func (input ResolveAttributesOutput) Validate() error {
	if input.CompoundBeacons == nil {
		return fmt.Errorf("input.CompoundBeacons is required but has a nil value.")
	}
	if input.VirtualFields == nil {
		return fmt.Errorf("input.VirtualFields is required but has a nil value.")
	}

	return nil
}

type ResolveAttributesInput struct {
	Item map[string]dynamodbtypes.AttributeValue

	TableName string

	Version *int32
}

func (input ResolveAttributesInput) Validate() error {
	if input.Item == nil {
		return fmt.Errorf("input.Item is required but has a nil value.")
	}
	if input.Aws_cryptography_dbEncryptionSdk_dynamoDb_transforms_ResolveAttributesInput_Item_Validate() != nil {
		return input.Aws_cryptography_dbEncryptionSdk_dynamoDb_transforms_ResolveAttributesInput_Item_Validate()
	}
	if len(input.TableName) < 3 {
		return fmt.Errorf("TableName has a minimum length of 3 but has the length of %d.", len(input.TableName))
	}
	if len(input.TableName) > 255 {
		return fmt.Errorf("TableName has a maximum length of 255 but has the length of %d.", len(input.TableName))
	}
	if input.Version != nil {
		if *input.Version < 1 {
			return fmt.Errorf("VersionNumber has a minimum of 1 but has the value of %d.", *input.Version)
		}
	}

	return nil
}

func (input ResolveAttributesInput) Com_amazonaws_dynamodb_AttributeMap_value_Validate(Value dynamodbtypes.AttributeValue) error {
	if Value == nil {
		return nil
	}
	switch unionType := Value.(type) {
	case *dynamodbtypes.AttributeValueMemberS:
	case *dynamodbtypes.AttributeValueMemberN:
	case *dynamodbtypes.AttributeValueMemberB:
	case *dynamodbtypes.AttributeValueMemberSS:
	case *dynamodbtypes.AttributeValueMemberNS:
	case *dynamodbtypes.AttributeValueMemberBS:
	case *dynamodbtypes.AttributeValueMemberM:
	case *dynamodbtypes.AttributeValueMemberL:
	case *dynamodbtypes.AttributeValueMemberNULL:
	case *dynamodbtypes.AttributeValueMemberBOOL:
	// Default case should not be reached.
	default:
		panic(fmt.Sprintf("Unhandled union type: %T ", unionType))
	}

	return nil
}
func (input ResolveAttributesInput) Com_amazonaws_dynamodb_MapAttributeValue_value_Validate(Value dynamodbtypes.AttributeValue) error {
	if Value == nil {
		return nil
	}
	switch unionType := Value.(type) {
	case *dynamodbtypes.AttributeValueMemberS:
	case *dynamodbtypes.AttributeValueMemberN:
	case *dynamodbtypes.AttributeValueMemberB:
	case *dynamodbtypes.AttributeValueMemberSS:
	case *dynamodbtypes.AttributeValueMemberNS:
	case *dynamodbtypes.AttributeValueMemberBS:
	case *dynamodbtypes.AttributeValueMemberM:
		if input.Com_amazonaws_dynamodb_AttributeValue_M_Validate(unionType.Value) != nil {
			return input.Com_amazonaws_dynamodb_AttributeValue_M_Validate(unionType.Value)
		}
	case *dynamodbtypes.AttributeValueMemberL:
	case *dynamodbtypes.AttributeValueMemberNULL:
	case *dynamodbtypes.AttributeValueMemberBOOL:
	// Default case should not be reached.
	default:
		panic(fmt.Sprintf("Unhandled union type: %T ", unionType))
	}

	return nil
}
func (input ResolveAttributesInput) Com_amazonaws_dynamodb_AttributeValue_M_Validate(Value map[string]dynamodbtypes.AttributeValue) error {
	for key, value := range Value {
		if len(key) < 0 {
			return fmt.Errorf("AttributeName has a minimum length of 0 but has the length of %d.", len(key))
		}
		if len(key) > 65535 {
			return fmt.Errorf("AttributeName has a maximum length of 65535 but has the length of %d.", len(key))
		}
		if input.Com_amazonaws_dynamodb_MapAttributeValue_value_Validate(value) != nil {
			return input.Com_amazonaws_dynamodb_MapAttributeValue_value_Validate(value)
		}
	}

	return nil
}
func (input ResolveAttributesInput) Com_amazonaws_dynamodb_ListAttributeValue_member_Validate(Value dynamodbtypes.AttributeValue) error {
	if Value == nil {
		return nil
	}
	switch unionType := Value.(type) {
	case *dynamodbtypes.AttributeValueMemberS:
	case *dynamodbtypes.AttributeValueMemberN:
	case *dynamodbtypes.AttributeValueMemberB:
	case *dynamodbtypes.AttributeValueMemberSS:
	case *dynamodbtypes.AttributeValueMemberNS:
	case *dynamodbtypes.AttributeValueMemberBS:
	case *dynamodbtypes.AttributeValueMemberM:
	case *dynamodbtypes.AttributeValueMemberL:
		if input.Com_amazonaws_dynamodb_AttributeValue_L_Validate(unionType.Value) != nil {
			return input.Com_amazonaws_dynamodb_AttributeValue_L_Validate(unionType.Value)
		}
	case *dynamodbtypes.AttributeValueMemberNULL:
	case *dynamodbtypes.AttributeValueMemberBOOL:
	// Default case should not be reached.
	default:
		panic(fmt.Sprintf("Unhandled union type: %T ", unionType))
	}

	return nil
}
func (input ResolveAttributesInput) Com_amazonaws_dynamodb_AttributeValue_L_Validate(Value []dynamodbtypes.AttributeValue) error {
	for _, item := range Value {
		if input.Com_amazonaws_dynamodb_ListAttributeValue_member_Validate(item) != nil {
			return input.Com_amazonaws_dynamodb_ListAttributeValue_member_Validate(item)
		}
	}

	return nil
}
func (input ResolveAttributesInput) Aws_cryptography_dbEncryptionSdk_dynamoDb_transforms_ResolveAttributesInput_Item_Validate() error {
	for key, value := range input.Item {
		if len(key) < 0 {
			return fmt.Errorf("AttributeName has a minimum length of 0 but has the length of %d.", len(key))
		}
		if len(key) > 65535 {
			return fmt.Errorf("AttributeName has a maximum length of 65535 but has the length of %d.", len(key))
		}
		if input.Com_amazonaws_dynamodb_AttributeMap_value_Validate(value) != nil {
			return input.Com_amazonaws_dynamodb_AttributeMap_value_Validate(value)
		}
	}

	return nil
}

type ExecuteStatementInputTransformInput struct {
	SdkInput dynamodb.ExecuteStatementInput
}

func (input ExecuteStatementInputTransformInput) Validate() error {

	return nil
}

type ExecuteStatementInputTransformOutput struct {
	TransformedInput dynamodb.ExecuteStatementInput
}

func (input ExecuteStatementInputTransformOutput) Validate() error {

	return nil
}

type GetItemInputTransformInput struct {
	SdkInput dynamodb.GetItemInput
}

func (input GetItemInputTransformInput) Validate() error {

	return nil
}

type GetItemInputTransformOutput struct {
	TransformedInput dynamodb.GetItemInput
}

func (input GetItemInputTransformOutput) Validate() error {

	return nil
}

type GetItemOutputTransformOutput struct {
	TransformedOutput dynamodb.GetItemOutput
}

func (input GetItemOutputTransformOutput) Validate() error {

	return nil
}

type BatchExecuteStatementInputTransformInput struct {
	SdkInput dynamodb.BatchExecuteStatementInput
}

func (input BatchExecuteStatementInputTransformInput) Validate() error {

	return nil
}

type BatchExecuteStatementInputTransformOutput struct {
	TransformedInput dynamodb.BatchExecuteStatementInput
}

func (input BatchExecuteStatementInputTransformOutput) Validate() error {

	return nil
}

type ExecuteTransactionInputTransformInput struct {
	SdkInput dynamodb.ExecuteTransactionInput
}

func (input ExecuteTransactionInputTransformInput) Validate() error {

	return nil
}

type ExecuteTransactionInputTransformOutput struct {
	TransformedInput dynamodb.ExecuteTransactionInput
}

func (input ExecuteTransactionInputTransformOutput) Validate() error {

	return nil
}

type ExecuteTransactionOutputTransformOutput struct {
	TransformedOutput dynamodb.ExecuteTransactionOutput
}

func (input ExecuteTransactionOutputTransformOutput) Validate() error {

	return nil
}

type TransactGetItemsOutputTransformOutput struct {
	TransformedOutput dynamodb.TransactGetItemsOutput
}

func (input TransactGetItemsOutputTransformOutput) Validate() error {

	return nil
}

type BatchGetItemInputTransformInput struct {
	SdkInput dynamodb.BatchGetItemInput
}

func (input BatchGetItemInputTransformInput) Validate() error {

	return nil
}

type BatchGetItemInputTransformOutput struct {
	TransformedInput dynamodb.BatchGetItemInput
}

func (input BatchGetItemInputTransformOutput) Validate() error {

	return nil
}

type TransactGetItemsInputTransformInput struct {
	SdkInput dynamodb.TransactGetItemsInput
}

func (input TransactGetItemsInputTransformInput) Validate() error {

	return nil
}

type TransactGetItemsInputTransformOutput struct {
	TransformedInput dynamodb.TransactGetItemsInput
}

func (input TransactGetItemsInputTransformOutput) Validate() error {

	return nil
}

type TransactWriteItemsOutputTransformOutput struct {
	TransformedOutput dynamodb.TransactWriteItemsOutput
}

func (input TransactWriteItemsOutputTransformOutput) Validate() error {

	return nil
}

type GetItemOutputTransformInput struct {
	OriginalInput dynamodb.GetItemInput

	SdkOutput dynamodb.GetItemOutput
}

func (input GetItemOutputTransformInput) Validate() error {

	return nil
}

type DeleteItemOutputTransformOutput struct {
	TransformedOutput dynamodb.DeleteItemOutput
}

func (input DeleteItemOutputTransformOutput) Validate() error {

	return nil
}

type ExecuteStatementOutputTransformOutput struct {
	TransformedOutput dynamodb.ExecuteStatementOutput
}

func (input ExecuteStatementOutputTransformOutput) Validate() error {

	return nil
}

type PutItemOutputTransformOutput struct {
	TransformedOutput dynamodb.PutItemOutput
}

func (input PutItemOutputTransformOutput) Validate() error {

	return nil
}

type QueryOutputTransformOutput struct {
	TransformedOutput dynamodb.QueryOutput
}

func (input QueryOutputTransformOutput) Validate() error {

	return nil
}

type ScanOutputTransformOutput struct {
	TransformedOutput dynamodb.ScanOutput
}

func (input ScanOutputTransformOutput) Validate() error {

	return nil
}

type UpdateItemOutputTransformOutput struct {
	TransformedOutput dynamodb.UpdateItemOutput
}

func (input UpdateItemOutputTransformOutput) Validate() error {

	return nil
}

type ExecuteTransactionOutputTransformInput struct {
	OriginalInput dynamodb.ExecuteTransactionInput

	SdkOutput dynamodb.ExecuteTransactionOutput
}

func (input ExecuteTransactionOutputTransformInput) Validate() error {

	return nil
}

type BatchExecuteStatementOutputTransformOutput struct {
	TransformedOutput dynamodb.BatchExecuteStatementOutput
}

func (input BatchExecuteStatementOutputTransformOutput) Validate() error {

	return nil
}

type BatchGetItemOutputTransformOutput struct {
	TransformedOutput dynamodb.BatchGetItemOutput
}

func (input BatchGetItemOutputTransformOutput) Validate() error {

	return nil
}

type TransactGetItemsOutputTransformInput struct {
	OriginalInput dynamodb.TransactGetItemsInput

	SdkOutput dynamodb.TransactGetItemsOutput
}

func (input TransactGetItemsOutputTransformInput) Validate() error {

	return nil
}

type ExecuteStatementOutputTransformInput struct {
	OriginalInput dynamodb.ExecuteStatementInput

	SdkOutput dynamodb.ExecuteStatementOutput
}

func (input ExecuteStatementOutputTransformInput) Validate() error {

	return nil
}

type ScanInputTransformInput struct {
	SdkInput dynamodb.ScanInput
}

func (input ScanInputTransformInput) Validate() error {

	return nil
}

type ScanInputTransformOutput struct {
	TransformedInput dynamodb.ScanInput
}

func (input ScanInputTransformOutput) Validate() error {

	return nil
}

type BatchWriteItemInputTransformInput struct {
	SdkInput dynamodb.BatchWriteItemInput
}

func (input BatchWriteItemInputTransformInput) Validate() error {

	return nil
}

type BatchWriteItemInputTransformOutput struct {
	TransformedInput dynamodb.BatchWriteItemInput
}

func (input BatchWriteItemInputTransformOutput) Validate() error {

	return nil
}

type BatchExecuteStatementOutputTransformInput struct {
	OriginalInput dynamodb.BatchExecuteStatementInput

	SdkOutput dynamodb.BatchExecuteStatementOutput
}

func (input BatchExecuteStatementOutputTransformInput) Validate() error {

	return nil
}

type BatchGetItemOutputTransformInput struct {
	OriginalInput dynamodb.BatchGetItemInput

	SdkOutput dynamodb.BatchGetItemOutput
}

func (input BatchGetItemOutputTransformInput) Validate() error {

	return nil
}

type DeleteItemInputTransformInput struct {
	SdkInput dynamodb.DeleteItemInput
}

func (input DeleteItemInputTransformInput) Validate() error {

	return nil
}

type DeleteItemInputTransformOutput struct {
	TransformedInput dynamodb.DeleteItemInput
}

func (input DeleteItemInputTransformOutput) Validate() error {

	return nil
}

type PutItemInputTransformInput struct {
	SdkInput dynamodb.PutItemInput
}

func (input PutItemInputTransformInput) Validate() error {

	return nil
}

type PutItemInputTransformOutput struct {
	TransformedInput dynamodb.PutItemInput
}

func (input PutItemInputTransformOutput) Validate() error {

	return nil
}

type GetNumberOfQueriesInput struct {
	Input dynamodb.QueryInput
}

func (input GetNumberOfQueriesInput) Validate() error {

	return nil
}

type QueryInputTransformInput struct {
	SdkInput dynamodb.QueryInput
}

func (input QueryInputTransformInput) Validate() error {

	return nil
}

type QueryInputTransformOutput struct {
	TransformedInput dynamodb.QueryInput
}

func (input QueryInputTransformOutput) Validate() error {

	return nil
}

type BatchWriteItemOutputTransformOutput struct {
	TransformedOutput dynamodb.BatchWriteItemOutput
}

func (input BatchWriteItemOutputTransformOutput) Validate() error {

	return nil
}

type ScanOutputTransformInput struct {
	OriginalInput dynamodb.ScanInput

	SdkOutput dynamodb.ScanOutput
}

func (input ScanOutputTransformInput) Validate() error {

	return nil
}

type UpdateItemInputTransformInput struct {
	SdkInput dynamodb.UpdateItemInput
}

func (input UpdateItemInputTransformInput) Validate() error {

	return nil
}

type UpdateItemInputTransformOutput struct {
	TransformedInput dynamodb.UpdateItemInput
}

func (input UpdateItemInputTransformOutput) Validate() error {

	return nil
}

type DeleteItemOutputTransformInput struct {
	OriginalInput dynamodb.DeleteItemInput

	SdkOutput dynamodb.DeleteItemOutput
}

func (input DeleteItemOutputTransformInput) Validate() error {

	return nil
}

type PutItemOutputTransformInput struct {
	OriginalInput dynamodb.PutItemInput

	SdkOutput dynamodb.PutItemOutput
}

func (input PutItemOutputTransformInput) Validate() error {

	return nil
}

type QueryOutputTransformInput struct {
	OriginalInput dynamodb.QueryInput

	SdkOutput dynamodb.QueryOutput
}

func (input QueryOutputTransformInput) Validate() error {

	return nil
}

type UpdateItemOutputTransformInput struct {
	OriginalInput dynamodb.UpdateItemInput

	SdkOutput dynamodb.UpdateItemOutput
}

func (input UpdateItemOutputTransformInput) Validate() error {

	return nil
}

type BatchWriteItemOutputTransformInput struct {
	OriginalInput dynamodb.BatchWriteItemInput

	SdkOutput dynamodb.BatchWriteItemOutput
}

func (input BatchWriteItemOutputTransformInput) Validate() error {

	return nil
}

type TransactWriteItemsInputTransformInput struct {
	SdkInput dynamodb.TransactWriteItemsInput
}

func (input TransactWriteItemsInputTransformInput) Validate() error {

	return nil
}

type TransactWriteItemsInputTransformOutput struct {
	TransformedInput dynamodb.TransactWriteItemsInput
}

func (input TransactWriteItemsInputTransformOutput) Validate() error {

	return nil
}

type TransactWriteItemsOutputTransformInput struct {
	OriginalInput dynamodb.TransactWriteItemsInput

	SdkOutput dynamodb.TransactWriteItemsOutput
}

func (input TransactWriteItemsOutputTransformInput) Validate() error {

	return nil
}

type AwsCryptographicMaterialProvidersReference struct {
}

func (input AwsCryptographicMaterialProvidersReference) Validate() error {

	return nil
}

type DynamoDbEncryptionReference struct {
}

func (input DynamoDbEncryptionReference) Validate() error {

	return nil
}

type DynamoDbItemEncryptorReference struct {
}

func (input DynamoDbItemEncryptorReference) Validate() error {

	return nil
}

type StructuredEncryptionReference struct {
}

func (input StructuredEncryptionReference) Validate() error {

	return nil
}

type DynamoDbEncryptionTransformsBaseException interface {
	// This is a dummy method to allow type assertion since Go empty interfaces
	// aren't useful for type assertion checks. No concrete class is expected to implement
	// this method. This is also not exported.
	interfaceBindingMethod()
}
