// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbsmithygenerated

import (
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/AwsCryptographyDbEncryptionSdkDynamoDbTypes"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/awscryptographydbencryptionsdkdynamodbsmithygeneratedtypes"
)

type BucketSelector struct {
	Impl AwsCryptographyDbEncryptionSdkDynamoDbTypes.IBucketSelector
}

func (this *BucketSelector) GetBucketNumber(params awscryptographydbencryptionsdkdynamodbsmithygeneratedtypes.GetBucketNumberInput) (*awscryptographydbencryptionsdkdynamodbsmithygeneratedtypes.GetBucketNumberOutput, error) {
	var dafny_request AwsCryptographyDbEncryptionSdkDynamoDbTypes.GetBucketNumberInput = GetBucketNumberInput_ToDafny(params)
	var dafny_response = this.Impl.GetBucketNumber(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyDbEncryptionSdkDynamoDbTypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetBucketNumberOutput_FromDafny(dafny_response.Dtor_value().(AwsCryptographyDbEncryptionSdkDynamoDbTypes.GetBucketNumberOutput))
	return &native_response, nil

}
