// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbsmithygenerated

import (
	"github.com/aws/aws-database-encryption-sdk-dynamodb/AwsCryptographyDbEncryptionSdkDynamoDbTypes"
)

type LegacyDynamoDbEncryptor struct {
	Impl AwsCryptographyDbEncryptionSdkDynamoDbTypes.ILegacyDynamoDbEncryptor
}
