// Code generated by smithy-go-codegen DO NOT EDIT.

package KMSwrapped

import (
	"context"

	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/kms/ComAmazonawsKmsTypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/kms/comamazonawskmssmithygenerated"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
	"github.com/aws/aws-sdk-go-v2/service/kms"
	"github.com/dafny-lang/DafnyRuntimeGo/v4/dafny"
)

type Shim struct {
	ComAmazonawsKmsTypes.IKMSClient
	Client *kms.Client
}

func (shim *Shim) CancelKeyDeletion(input ComAmazonawsKmsTypes.CancelKeyDeletionRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.CancelKeyDeletionInput_FromDafny(input)
	var native_response, native_error = shim.Client.CancelKeyDeletion(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.CancelKeyDeletionOutput_ToDafny(*native_response))
}

func (shim *Shim) ConnectCustomKeyStore(input ComAmazonawsKmsTypes.ConnectCustomKeyStoreRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ConnectCustomKeyStoreInput_FromDafny(input)
	var native_response, native_error = shim.Client.ConnectCustomKeyStore(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ConnectCustomKeyStoreOutput_ToDafny(*native_response))
}

func (shim *Shim) CreateAlias(input ComAmazonawsKmsTypes.CreateAliasRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.CreateAliasInput_FromDafny(input)
	var _, native_error = shim.Client.CreateAlias(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) CreateCustomKeyStore(input ComAmazonawsKmsTypes.CreateCustomKeyStoreRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.CreateCustomKeyStoreInput_FromDafny(input)
	var native_response, native_error = shim.Client.CreateCustomKeyStore(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.CreateCustomKeyStoreOutput_ToDafny(*native_response))
}

func (shim *Shim) CreateGrant(input ComAmazonawsKmsTypes.CreateGrantRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.CreateGrantInput_FromDafny(input)
	var native_response, native_error = shim.Client.CreateGrant(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.CreateGrantOutput_ToDafny(*native_response))
}

func (shim *Shim) CreateKey(input ComAmazonawsKmsTypes.CreateKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.CreateKeyInput_FromDafny(input)
	var native_response, native_error = shim.Client.CreateKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.CreateKeyOutput_ToDafny(*native_response))
}

func (shim *Shim) Decrypt(input ComAmazonawsKmsTypes.DecryptRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DecryptInput_FromDafny(input)
	var native_response, native_error = shim.Client.Decrypt(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DecryptOutput_ToDafny(*native_response))
}

func (shim *Shim) DeleteAlias(input ComAmazonawsKmsTypes.DeleteAliasRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DeleteAliasInput_FromDafny(input)
	var _, native_error = shim.Client.DeleteAlias(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) DeleteCustomKeyStore(input ComAmazonawsKmsTypes.DeleteCustomKeyStoreRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DeleteCustomKeyStoreInput_FromDafny(input)
	var native_response, native_error = shim.Client.DeleteCustomKeyStore(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DeleteCustomKeyStoreOutput_ToDafny(*native_response))
}

func (shim *Shim) DeleteImportedKeyMaterial(input ComAmazonawsKmsTypes.DeleteImportedKeyMaterialRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DeleteImportedKeyMaterialInput_FromDafny(input)
	var _, native_error = shim.Client.DeleteImportedKeyMaterial(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) DeriveSharedSecret(input ComAmazonawsKmsTypes.DeriveSharedSecretRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DeriveSharedSecretInput_FromDafny(input)
	var native_response, native_error = shim.Client.DeriveSharedSecret(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DeriveSharedSecretOutput_ToDafny(*native_response))
}

func (shim *Shim) DescribeCustomKeyStores(input ComAmazonawsKmsTypes.DescribeCustomKeyStoresRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DescribeCustomKeyStoresInput_FromDafny(input)
	var native_response, native_error = shim.Client.DescribeCustomKeyStores(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DescribeCustomKeyStoresOutput_ToDafny(*native_response))
}

func (shim *Shim) DescribeKey(input ComAmazonawsKmsTypes.DescribeKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DescribeKeyInput_FromDafny(input)
	var native_response, native_error = shim.Client.DescribeKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DescribeKeyOutput_ToDafny(*native_response))
}

func (shim *Shim) DisableKey(input ComAmazonawsKmsTypes.DisableKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DisableKeyInput_FromDafny(input)
	var _, native_error = shim.Client.DisableKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) DisableKeyRotation(input ComAmazonawsKmsTypes.DisableKeyRotationRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DisableKeyRotationInput_FromDafny(input)
	var _, native_error = shim.Client.DisableKeyRotation(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) DisconnectCustomKeyStore(input ComAmazonawsKmsTypes.DisconnectCustomKeyStoreRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.DisconnectCustomKeyStoreInput_FromDafny(input)
	var native_response, native_error = shim.Client.DisconnectCustomKeyStore(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.DisconnectCustomKeyStoreOutput_ToDafny(*native_response))
}

func (shim *Shim) EnableKey(input ComAmazonawsKmsTypes.EnableKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.EnableKeyInput_FromDafny(input)
	var _, native_error = shim.Client.EnableKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) EnableKeyRotation(input ComAmazonawsKmsTypes.EnableKeyRotationRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.EnableKeyRotationInput_FromDafny(input)
	var _, native_error = shim.Client.EnableKeyRotation(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) Encrypt(input ComAmazonawsKmsTypes.EncryptRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.EncryptInput_FromDafny(input)
	var native_response, native_error = shim.Client.Encrypt(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.EncryptOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateDataKey(input ComAmazonawsKmsTypes.GenerateDataKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateDataKeyInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateDataKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateDataKeyOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateDataKeyPair(input ComAmazonawsKmsTypes.GenerateDataKeyPairRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateDataKeyPairInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateDataKeyPair(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateDataKeyPairOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateDataKeyPairWithoutPlaintext(input ComAmazonawsKmsTypes.GenerateDataKeyPairWithoutPlaintextRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateDataKeyPairWithoutPlaintextInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateDataKeyPairWithoutPlaintext(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateDataKeyPairWithoutPlaintextOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateDataKeyWithoutPlaintext(input ComAmazonawsKmsTypes.GenerateDataKeyWithoutPlaintextRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateDataKeyWithoutPlaintextInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateDataKeyWithoutPlaintext(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateDataKeyWithoutPlaintextOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateMac(input ComAmazonawsKmsTypes.GenerateMacRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateMacInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateMac(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateMacOutput_ToDafny(*native_response))
}

func (shim *Shim) GenerateRandom(input ComAmazonawsKmsTypes.GenerateRandomRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GenerateRandomInput_FromDafny(input)
	var native_response, native_error = shim.Client.GenerateRandom(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GenerateRandomOutput_ToDafny(*native_response))
}

func (shim *Shim) GetKeyPolicy(input ComAmazonawsKmsTypes.GetKeyPolicyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GetKeyPolicyInput_FromDafny(input)
	var native_response, native_error = shim.Client.GetKeyPolicy(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GetKeyPolicyOutput_ToDafny(*native_response))
}

func (shim *Shim) GetKeyRotationStatus(input ComAmazonawsKmsTypes.GetKeyRotationStatusRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GetKeyRotationStatusInput_FromDafny(input)
	var native_response, native_error = shim.Client.GetKeyRotationStatus(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GetKeyRotationStatusOutput_ToDafny(*native_response))
}

func (shim *Shim) GetParametersForImport(input ComAmazonawsKmsTypes.GetParametersForImportRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GetParametersForImportInput_FromDafny(input)
	var native_response, native_error = shim.Client.GetParametersForImport(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GetParametersForImportOutput_ToDafny(*native_response))
}

func (shim *Shim) GetPublicKey(input ComAmazonawsKmsTypes.GetPublicKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.GetPublicKeyInput_FromDafny(input)
	var native_response, native_error = shim.Client.GetPublicKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.GetPublicKeyOutput_ToDafny(*native_response))
}

func (shim *Shim) ImportKeyMaterial(input ComAmazonawsKmsTypes.ImportKeyMaterialRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ImportKeyMaterialInput_FromDafny(input)
	var native_response, native_error = shim.Client.ImportKeyMaterial(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ImportKeyMaterialOutput_ToDafny(*native_response))
}

func (shim *Shim) ListAliases(input ComAmazonawsKmsTypes.ListAliasesRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListAliasesInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListAliases(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListAliasesOutput_ToDafny(*native_response))
}

func (shim *Shim) ListGrants(input ComAmazonawsKmsTypes.ListGrantsRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListGrantsInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListGrants(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListGrantsOutput_ToDafny(*native_response))
}

func (shim *Shim) ListKeyPolicies(input ComAmazonawsKmsTypes.ListKeyPoliciesRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListKeyPoliciesInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListKeyPolicies(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListKeyPoliciesOutput_ToDafny(*native_response))
}

func (shim *Shim) ListKeyRotations(input ComAmazonawsKmsTypes.ListKeyRotationsRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListKeyRotationsInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListKeyRotations(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListKeyRotationsOutput_ToDafny(*native_response))
}

func (shim *Shim) ListKeys(input ComAmazonawsKmsTypes.ListKeysRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListKeysInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListKeys(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListKeysOutput_ToDafny(*native_response))
}

func (shim *Shim) ListResourceTags(input ComAmazonawsKmsTypes.ListResourceTagsRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ListResourceTagsInput_FromDafny(input)
	var native_response, native_error = shim.Client.ListResourceTags(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ListResourceTagsOutput_ToDafny(*native_response))
}

func (shim *Shim) PutKeyPolicy(input ComAmazonawsKmsTypes.PutKeyPolicyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.PutKeyPolicyInput_FromDafny(input)
	var _, native_error = shim.Client.PutKeyPolicy(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) ReEncrypt(input ComAmazonawsKmsTypes.ReEncryptRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ReEncryptInput_FromDafny(input)
	var native_response, native_error = shim.Client.ReEncrypt(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ReEncryptOutput_ToDafny(*native_response))
}

func (shim *Shim) ReplicateKey(input ComAmazonawsKmsTypes.ReplicateKeyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ReplicateKeyInput_FromDafny(input)
	var native_response, native_error = shim.Client.ReplicateKey(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ReplicateKeyOutput_ToDafny(*native_response))
}

func (shim *Shim) RetireGrant(input ComAmazonawsKmsTypes.RetireGrantRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.RetireGrantInput_FromDafny(input)
	var _, native_error = shim.Client.RetireGrant(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) RevokeGrant(input ComAmazonawsKmsTypes.RevokeGrantRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.RevokeGrantInput_FromDafny(input)
	var _, native_error = shim.Client.RevokeGrant(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) RotateKeyOnDemand(input ComAmazonawsKmsTypes.RotateKeyOnDemandRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.RotateKeyOnDemandInput_FromDafny(input)
	var native_response, native_error = shim.Client.RotateKeyOnDemand(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.RotateKeyOnDemandOutput_ToDafny(*native_response))
}

func (shim *Shim) ScheduleKeyDeletion(input ComAmazonawsKmsTypes.ScheduleKeyDeletionRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.ScheduleKeyDeletionInput_FromDafny(input)
	var native_response, native_error = shim.Client.ScheduleKeyDeletion(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.ScheduleKeyDeletionOutput_ToDafny(*native_response))
}

func (shim *Shim) Sign(input ComAmazonawsKmsTypes.SignRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.SignInput_FromDafny(input)
	var native_response, native_error = shim.Client.Sign(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.SignOutput_ToDafny(*native_response))
}

func (shim *Shim) TagResource(input ComAmazonawsKmsTypes.TagResourceRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.TagResourceInput_FromDafny(input)
	var _, native_error = shim.Client.TagResource(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) UntagResource(input ComAmazonawsKmsTypes.UntagResourceRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.UntagResourceInput_FromDafny(input)
	var _, native_error = shim.Client.UntagResource(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) UpdateAlias(input ComAmazonawsKmsTypes.UpdateAliasRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.UpdateAliasInput_FromDafny(input)
	var _, native_error = shim.Client.UpdateAlias(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) UpdateCustomKeyStore(input ComAmazonawsKmsTypes.UpdateCustomKeyStoreRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.UpdateCustomKeyStoreInput_FromDafny(input)
	var native_response, native_error = shim.Client.UpdateCustomKeyStore(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.UpdateCustomKeyStoreOutput_ToDafny(*native_response))
}

func (shim *Shim) UpdateKeyDescription(input ComAmazonawsKmsTypes.UpdateKeyDescriptionRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.UpdateKeyDescriptionInput_FromDafny(input)
	var _, native_error = shim.Client.UpdateKeyDescription(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) UpdatePrimaryRegion(input ComAmazonawsKmsTypes.UpdatePrimaryRegionRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.UpdatePrimaryRegionInput_FromDafny(input)
	var _, native_error = shim.Client.UpdatePrimaryRegion(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(dafny.TupleOf())
}

func (shim *Shim) Verify(input ComAmazonawsKmsTypes.VerifyRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.VerifyInput_FromDafny(input)
	var native_response, native_error = shim.Client.Verify(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.VerifyOutput_ToDafny(*native_response))
}

func (shim *Shim) VerifyMac(input ComAmazonawsKmsTypes.VerifyMacRequest) Wrappers.Result {
	var native_request = comamazonawskmssmithygenerated.VerifyMacInput_FromDafny(input)
	var native_response, native_error = shim.Client.VerifyMac(context.Background(), &native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(comamazonawskmssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(comamazonawskmssmithygenerated.VerifyMacOutput_ToDafny(*native_response))
}
