// Class __default
// Dafny class __default compiled into Java
package TransactGetItemsTransform_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> Input(DdbMiddlewareConfig_Compile.Config config, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsInputTransformOutput.create((input).dtor_sdkInput()));
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> Output(DdbMiddlewareConfig_Compile.Config config, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput.Default());
    if (DynamoDbMiddlewareSupport_Compile.__default.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>NoList(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor(), ((input).dtor_sdkOutput()).dtor_Responses())) {
      output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput.create((input).dtor_sdkOutput()));
      return output;
    }
    if (!java.util.Objects.equals(java.math.BigInteger.valueOf(((((input).dtor_sdkOutput()).dtor_Responses()).dtor_value()).length()), java.math.BigInteger.valueOf((((input).dtor_originalInput()).dtor_TransactItems()).length()))) {
      output = DdbMiddlewareConfig_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput>MakeError(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor(), dafny.DafnySequence.asString("Invalid TransactGetItems response for original request: Number of items returned must equal number of items requested."));
      return output;
    }
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> _0_decryptedItems;
    _0_decryptedItems = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> empty(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor());
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> _1_encryptedItems;
    _1_encryptedItems = (((input).dtor_sdkOutput()).dtor_Responses()).dtor_value();
    java.math.BigInteger _hi0 = java.math.BigInteger.valueOf((_1_encryptedItems).length());
    for (java.math.BigInteger _2_x = java.math.BigInteger.ZERO; _2_x.compareTo(_hi0) < 0; _2_x = _2_x.add(java.math.BigInteger.ONE)) {
      dafny.DafnySequence<? extends Character> _3_tableName;
      _3_tableName = ((((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItem)(java.lang.Object)((((input).dtor_originalInput()).dtor_TransactItems()).select(dafny.Helpers.toInt((_2_x)))))).dtor_Get()).dtor_TableName();
      if (!((config).dtor_tableEncryptionConfigs()).<dafny.DafnySequence<? extends Character>>contains(_3_tableName)) {
        _0_decryptedItems = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>concatenate(_0_decryptedItems, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor(), ((software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse)(java.lang.Object)((_1_encryptedItems).select(dafny.Helpers.toInt((_2_x)))))));
      } else {
        DdbMiddlewareConfig_Compile.TableConfig _4_tableConfig;
        _4_tableConfig = ((DdbMiddlewareConfig_Compile.TableConfig)(java.lang.Object)(((config).dtor_tableEncryptionConfigs()).get(_3_tableName)));
        if (DynamoDbMiddlewareSupport_Compile.__default.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>NoMap(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor(), (((software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse)(java.lang.Object)((_1_encryptedItems).select(dafny.Helpers.toInt((_2_x)))))).dtor_Item())) {
          _0_decryptedItems = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>concatenate(_0_decryptedItems, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor())))));
        } else {
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _5_decryptRes;
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _out0;
          _out0 = ((_4_tableConfig).dtor_itemEncryptor()).DecryptItem(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemInput.create(((((software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse)(java.lang.Object)((_1_encryptedItems).select(dafny.Helpers.toInt((_2_x)))))).dtor_Item()).dtor_value()));
          _5_decryptRes = _out0;
          Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _6_valueOrError0 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput.Default());
          _6_valueOrError0 = DdbMiddlewareConfig_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput>MapError(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput._typeDescriptor(), _5_decryptRes);
          if ((_6_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
            output = (_6_valueOrError0).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor());
            return output;
          }
          software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput _7_decrypted;
          _7_decrypted = (_6_valueOrError0).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DecryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
          Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _8_valueOrError1 = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> empty());
          _8_valueOrError1 = DynamoDbMiddlewareSupport_Compile.__default.RemoveBeacons(_4_tableConfig, (_7_decrypted).dtor_plaintextItem());
          if ((_8_valueOrError1).IsFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
            output = (_8_valueOrError1).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput>PropagateFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor());
            return output;
          }
          dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _9_item;
          _9_item = (_8_valueOrError1).Extract(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
          _0_decryptedItems = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>concatenate(_0_decryptedItems, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>create_Some(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), _9_item))));
        }
      }
    }
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse> _pat_let_tv0 = _0_decryptedItems;
    output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactGetItemsOutputTransformOutput.create(((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput>Let((input).dtor_sdkOutput(), boxed80 -> {
  software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput _pat_let41_0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(boxed80));
  return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput>Let(_pat_let41_0, boxed81 -> {
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput _10_dt__update__tmp_h0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(boxed81));
    return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>>, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput>Let(Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>>create_Some(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse._typeDescriptor()), _pat_let_tv0), boxed82 -> {
      Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>> _pat_let42_0 = ((Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>>)(java.lang.Object)(boxed82));
      return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput)(java.lang.Object)(dafny.Helpers.<Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>>, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput>Let(_pat_let42_0, boxed83 -> {
        Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>> _11_dt__update_hResponses_h0 = ((Wrappers_Compile.Option<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemResponse>>)(java.lang.Object)(boxed83));
        return software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactGetItemsOutput.create((_10_dt__update__tmp_h0).dtor_ConsumedCapacity(), _11_dt__update_hResponses_h0);
      }
      )));
    }
    )));
  }
  )));
}
)))));
    return output;
  }
  @Override
  public java.lang.String toString() {
    return "TransactGetItemsTransform._default";
  }
}
