// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkstructuredencryptionsmithygeneratedtypes

import (
	"fmt"
)

type StructuredEncryptionException struct {
	StructuredEncryptionBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e StructuredEncryptionException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
