// Class __default
// Dafny class __default compiled into Java
package TransactWriteItemsTransform_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static boolean IsValid(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem item) {
    return (((((item).dtor_Put()).is_Some()) || (((item).dtor_Update()).is_Some())) || (((item).dtor_Delete()).is_Some())) || (((item).dtor_ConditionCheck()).is_Some());
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> Input(DdbMiddlewareConfig_Compile.Config config, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformInput, Boolean>)(_1_input) -> dafny.Helpers.Quantifier((((_1_input).dtor_sdkInput()).dtor_TransactItems()).UniqueElements(), true, ((_forall_var_0_boxed0) -> {
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _forall_var_0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem)(java.lang.Object)(_forall_var_0_boxed0));
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _2_item = (software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem)_forall_var_0;
      return !((((_1_input).dtor_sdkInput()).dtor_TransactItems()).contains(_2_item)) || (__default.IsValid(_2_item));
    }))).apply(input), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("Each item in TransactWriteItems must specify at least one supported operation")));
    if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
      output = (_0_valueOrError0).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
      return output;
    }
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _3_result;
    _3_result = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> empty(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor());
    java.math.BigInteger _hi0 = java.math.BigInteger.valueOf((((input).dtor_sdkInput()).dtor_TransactItems()).length());
    for (java.math.BigInteger _4_x = java.math.BigInteger.ZERO; _4_x.compareTo(_hi0) < 0; _4_x = _4_x.add(java.math.BigInteger.ONE)) {
      software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _5_item;
      _5_item = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem)(java.lang.Object)((((input).dtor_sdkInput()).dtor_TransactItems()).select(dafny.Helpers.toInt((_4_x)))));
      if ((((_5_item).dtor_ConditionCheck()).is_Some()) && (((config).dtor_tableEncryptionConfigs()).<dafny.DafnySequence<? extends Character>>contains((((_5_item).dtor_ConditionCheck()).dtor_value()).dtor_TableName()))) {
        DdbMiddlewareConfig_Compile.TableConfig _6_tableConfig;
        _6_tableConfig = ((DdbMiddlewareConfig_Compile.TableConfig)(java.lang.Object)(((config).dtor_tableEncryptionConfigs()).get((((_5_item).dtor_ConditionCheck()).dtor_value()).dtor_TableName())));
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _7_valueOrError1 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        _7_valueOrError1 = DynamoDbMiddlewareSupport_Compile.__default.TestConditionExpression(_6_tableConfig, Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_Some(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), (((_5_item).dtor_ConditionCheck()).dtor_value()).dtor_ConditionExpression()), (((_5_item).dtor_ConditionCheck()).dtor_value()).dtor_ExpressionAttributeNames(), (((_5_item).dtor_ConditionCheck()).dtor_value()).dtor_ExpressionAttributeValues());
        if ((_7_valueOrError1).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_7_valueOrError1).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _8___v0;
        _8___v0 = (_7_valueOrError1).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
      }
      if ((((_5_item).dtor_Delete()).is_Some()) && (((config).dtor_tableEncryptionConfigs()).<dafny.DafnySequence<? extends Character>>contains((((_5_item).dtor_Delete()).dtor_value()).dtor_TableName()))) {
        DdbMiddlewareConfig_Compile.TableConfig _9_tableConfig;
        _9_tableConfig = ((DdbMiddlewareConfig_Compile.TableConfig)(java.lang.Object)(((config).dtor_tableEncryptionConfigs()).get((((_5_item).dtor_Delete()).dtor_value()).dtor_TableName())));
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _10_valueOrError2 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        _10_valueOrError2 = DynamoDbMiddlewareSupport_Compile.__default.TestConditionExpression(_9_tableConfig, (((_5_item).dtor_Delete()).dtor_value()).dtor_ConditionExpression(), (((_5_item).dtor_Delete()).dtor_value()).dtor_ExpressionAttributeNames(), (((_5_item).dtor_Delete()).dtor_value()).dtor_ExpressionAttributeValues());
        if ((_10_valueOrError2).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_10_valueOrError2).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _11___v1;
        _11___v1 = (_10_valueOrError2).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
      }
      if ((((_5_item).dtor_Update()).is_Some()) && (((config).dtor_tableEncryptionConfigs()).<dafny.DafnySequence<? extends Character>>contains((((_5_item).dtor_Update()).dtor_value()).dtor_TableName()))) {
        DdbMiddlewareConfig_Compile.TableConfig _12_tableConfig;
        _12_tableConfig = ((DdbMiddlewareConfig_Compile.TableConfig)(java.lang.Object)(((config).dtor_tableEncryptionConfigs()).get((((_5_item).dtor_Update()).dtor_value()).dtor_TableName())));
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _13_valueOrError3 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        _13_valueOrError3 = DynamoDbMiddlewareSupport_Compile.__default.TestUpdateExpression(_12_tableConfig, Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_Some(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), (((_5_item).dtor_Update()).dtor_value()).dtor_UpdateExpression()), (((_5_item).dtor_Update()).dtor_value()).dtor_ExpressionAttributeNames(), (((_5_item).dtor_Update()).dtor_value()).dtor_ExpressionAttributeValues());
        if ((_13_valueOrError3).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_13_valueOrError3).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _14___v2;
        _14___v2 = (_13_valueOrError3).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _15_valueOrError4 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        _15_valueOrError4 = DynamoDbMiddlewareSupport_Compile.__default.TestConditionExpression(_12_tableConfig, (((_5_item).dtor_Update()).dtor_value()).dtor_ConditionExpression(), (((_5_item).dtor_Update()).dtor_value()).dtor_ExpressionAttributeNames(), (((_5_item).dtor_Update()).dtor_value()).dtor_ExpressionAttributeValues());
        if ((_15_valueOrError4).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_15_valueOrError4).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _16___v3;
        _16___v3 = (_15_valueOrError4).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
      }
      if ((((_5_item).dtor_Put()).is_Some()) && (!(DdbMiddlewareConfig_Compile.__default.IsPlainWrite(config, (((_5_item).dtor_Put()).dtor_value()).dtor_TableName())))) {
        DdbMiddlewareConfig_Compile.TableConfig _17_tableConfig;
        _17_tableConfig = ((DdbMiddlewareConfig_Compile.TableConfig)(java.lang.Object)(((config).dtor_tableEncryptionConfigs()).get((((_5_item).dtor_Put()).dtor_value()).dtor_TableName())));
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _18_valueOrError5 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out0;
        _out0 = DynamoDbMiddlewareSupport_Compile.__default.IsWriteable(_17_tableConfig, (((_5_item).dtor_Put()).dtor_value()).dtor_Item());
        _18_valueOrError5 = _out0;
        if ((_18_valueOrError5).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_18_valueOrError5).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _19___v4;
        _19___v4 = (_18_valueOrError5).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _20_valueOrError6 = Wrappers_Compile.Result.<Boolean, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), false);
        _20_valueOrError6 = DynamoDbMiddlewareSupport_Compile.__default.TestConditionExpression(_17_tableConfig, (((_5_item).dtor_Put()).dtor_value()).dtor_ConditionExpression(), (((_5_item).dtor_Put()).dtor_value()).dtor_ExpressionAttributeNames(), (((_5_item).dtor_Put()).dtor_value()).dtor_ExpressionAttributeValues());
        if ((_20_valueOrError6).IsFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_20_valueOrError6).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        boolean _21___v5;
        _21___v5 = (_20_valueOrError6).Extract(dafny.TypeDescriptor.BOOLEAN, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _22_valueOrError7 = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> empty());
        Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out1;
        _out1 = DynamoDbMiddlewareSupport_Compile.__default.AddSignedBeacons(_17_tableConfig, (((_5_item).dtor_Put()).dtor_value()).dtor_Item());
        _22_valueOrError7 = _out1;
        if ((_22_valueOrError7).IsFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_22_valueOrError7).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _23_beaconItem;
        _23_beaconItem = (_22_valueOrError7).Extract(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _24_encryptRes;
        Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _out2;
        _out2 = ((_17_tableConfig).dtor_itemEncryptor()).EncryptItem(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemInput.create(_23_beaconItem));
        _24_encryptRes = _out2;
        Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _25_valueOrError8 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput.Default());
        _25_valueOrError8 = DdbMiddlewareConfig_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput>MapError(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput._typeDescriptor(), _24_encryptRes);
        if ((_25_valueOrError8).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_25_valueOrError8).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput _26_encrypted;
        _26_encrypted = (_25_valueOrError8).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _27_valueOrError9 = Wrappers_Compile.Result.<Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>Default(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)));
        _27_valueOrError9 = DynamoDbMiddlewareSupport_Compile.__default.GetKeyIdFromHeader(_17_tableConfig, _26_encrypted);
        if ((_27_valueOrError9).IsFailure(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_27_valueOrError9).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        Wrappers_Compile.Option<dafny.DafnySequence<? extends Character>> _28_keyId;
        _28_keyId = (_27_valueOrError9).Extract(Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _29_valueOrError10 = Wrappers_Compile.Result.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), dafny.DafnyMap.<dafny.DafnySequence<? extends Character>,software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> empty());
        Wrappers_Compile.Result<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out3;
        _out3 = DynamoDbMiddlewareSupport_Compile.__default.GetEncryptedBeacons(_17_tableConfig, (((_5_item).dtor_Put()).dtor_value()).dtor_Item(), DynamoDbEncryptionUtil_Compile.__default.MaybeFromOptionKeyId(_28_keyId));
        _29_valueOrError10 = _out3;
        if ((_29_valueOrError10).IsFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
          output = (_29_valueOrError10).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
          return output;
        }
        dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _30_beaconAttrs;
        _30_beaconAttrs = (_29_valueOrError10).Extract(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor()), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
        software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.EncryptItemOutput _pat_let_tv0 = _26_encrypted;
        dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _pat_let_tv1 = _30_beaconAttrs;
        Wrappers_Compile.Option<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put> _31_put;
        _31_put = Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.Put._typeDescriptor(), ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put, software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>Let(((_5_item).dtor_Put()).dtor_value(), boxed68 -> {
  software.amazon.cryptography.services.dynamodb.internaldafny.types.Put _pat_let35_0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(boxed68));
  return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put, software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>Let(_pat_let35_0, boxed69 -> {
    software.amazon.cryptography.services.dynamodb.internaldafny.types.Put _32_dt__update__tmp_h0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(boxed69));
    return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(dafny.Helpers.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>Let(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>merge((_pat_let_tv0).dtor_encryptedItem(), _pat_let_tv1), boxed70 -> {
      dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _pat_let36_0 = ((dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>)(java.lang.Object)(boxed70));
      return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.Put)(java.lang.Object)(dafny.Helpers.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>, software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>Let(_pat_let36_0, boxed71 -> {
        dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> _33_dt__update_hItem_h0 = ((dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>)(java.lang.Object)(boxed71));
        return software.amazon.cryptography.services.dynamodb.internaldafny.types.Put.create(_33_dt__update_hItem_h0, (_32_dt__update__tmp_h0).dtor_TableName(), (_32_dt__update__tmp_h0).dtor_ConditionExpression(), (_32_dt__update__tmp_h0).dtor_ExpressionAttributeNames(), (_32_dt__update__tmp_h0).dtor_ExpressionAttributeValues(), (_32_dt__update__tmp_h0).dtor_ReturnValuesOnConditionCheckFailure());
      }
      )));
    }
    )));
  }
  )));
}
))));
        software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _34_newItem;
        software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _35_dt__update__tmp_h1 = _5_item;
        Wrappers_Compile.Option<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put> _36_dt__update_hPut_h0 = _31_put;
        _34_newItem = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem.create((_35_dt__update__tmp_h1).dtor_ConditionCheck(), _36_dt__update_hPut_h0, (_35_dt__update__tmp_h1).dtor_Delete(), (_35_dt__update__tmp_h1).dtor_Update());
        _3_result = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>concatenate(_3_result, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), _34_newItem));
      } else {
        _3_result = dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>concatenate(_3_result, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), _5_item));
      }
    }
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _37_valueOrError11 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    _37_valueOrError11 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), java.util.Objects.equals(java.math.BigInteger.valueOf((((input).dtor_sdkInput()).dtor_TransactItems()).length()), java.math.BigInteger.valueOf((_3_result).length())), DdbMiddlewareConfig_Compile.__default.E(dafny.DafnySequence.asString("")));
    if ((_37_valueOrError11).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())) {
      output = (_37_valueOrError11).<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor());
      return output;
    }
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _pat_let_tv2 = _3_result;
    output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput.create(((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput>Let((input).dtor_sdkInput(), boxed72 -> {
  software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _pat_let37_0 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(boxed72));
  return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(dafny.Helpers.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput>Let(_pat_let37_0, boxed73 -> {
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _38_dt__update__tmp_h2 = ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(boxed73));
    return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput>Let(_pat_let_tv2, boxed74 -> {
      dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _pat_let38_0 = ((dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>)(java.lang.Object)(boxed74));
      return ((software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput)(java.lang.Object)(dafny.Helpers.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>, software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput>Let(_pat_let38_0, boxed75 -> {
        dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _39_dt__update_hTransactItems_h0 = ((dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem>)(java.lang.Object)(boxed75));
        return software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_39_dt__update_hTransactItems_h0, (_38_dt__update__tmp_h2).dtor_ReturnConsumedCapacity(), (_38_dt__update__tmp_h2).dtor_ReturnItemCollectionMetrics(), (_38_dt__update__tmp_h2).dtor_ClientRequestToken());
      }
      )));
    }
    )));
  }
  )));
}
)))));
    return output;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> Output(DdbMiddlewareConfig_Compile.Config config, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformInput input)
  {
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput.Default());
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput _0_finalResult;
    _0_finalResult = (input).dtor_sdkOutput();
    output = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>create_Success(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput.create(_0_finalResult));
    return output;
  }
  @Override
  public java.lang.String toString() {
    return "TransactWriteItemsTransform._default";
  }
}
