// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographykeystoresmithygeneratedtypes

import (
	"fmt"
)

type KeyStoreException struct {
	KeyStoreBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e KeyStoreException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
