AWSTemplateFormatVersion: "2010-09-09"
Description: "DDB Table and IAM Managed Policies/Role for DynamoDbEncryption testing"

Parameters:
  TableName:
    Type: String
    Description: Test Table Name
    Default: DynamoDbEncryptionInterceptorTestTable
  TableWithSimpleBeaconIndexName:
    Type: String
    Description: Simple Beacons Test Table Name
    Default: SimpleBeaconTestTable
  TableWithComplexBeaconIndexName:
    Type: String
    Description: Complex Beacons Test Table Name
    Default: ComplexBeaconTestTable
  ProjectName:
    Type: String
    Description: A prefix that will be applied to any names
    Default: DDBEC-Dafny
  GitHubRepo:
    Type: String
    Description: GitHub Repo that invokes CI
    Default: awslabs/aws-dynamodb-encryption-dafny

Resources:
  TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "partition_key"
          AttributeType: "S"
        - AttributeName: "sort_key"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "partition_key"
          KeyType: "HASH"
        - AttributeName: "sort_key"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref TableName

    TestTableWithSimpleBeaconIndex:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "partition_key"
            AttributeType: "S"
          - AttributeName: "sort_key"
            AttributeType: "N"
          - AttributeName: "beacon_str_attr"
            AttributeType: "S"
          - AttributeName: "beacon_num_attr"
            AttributeType: "N"
        GlobalSecondaryIndexes:
          - IndexName: "Example-Beacon-Index"
            KeySchema:
              - AttributeName: "beacon_str_attr"
                KeyType: "HASH"
              - AttributeName: "beacon_num_attr"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: "5"
              WriteCapacityUnits: "5"
        KeySchema:
          - AttributeName: "partition_key"
            KeyType: "HASH"
          - AttributeName: "sort_key"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: !Ref TableWithSimpleBeaconIndexName

    # This schema is modeled off of
    # https://github.com/aws-samples/searchable-encryption-dynamodb-howto/blob/main/BeaconPOC/Demo.md
    TestTableWithComplexBeaconIndex:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
          - AttributeName: "PK1"
            AttributeType: "S"
          - AttributeName: "SK1"
            AttributeType: "S"
          - AttributeName: "PK2"
            AttributeType: "S"
          - AttributeName: "SK2"
            AttributeType: "S"
          - AttributeName: "PK3"
            AttributeType: "S"
          - AttributeName: "SK3"
            AttributeType: "S"
        GlobalSecondaryIndexes:
          - IndexName: "GSI-1"
            KeySchema:
              - AttributeName: "PK1"
                KeyType: "HASH"
              - AttributeName: "SK1"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: "5"
              WriteCapacityUnits: "5"
          - IndexName: "GSI-2"
            KeySchema:
              - AttributeName: "PK2"
                KeyType: "HASH"
              - AttributeName: "SK2"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: "5"
              WriteCapacityUnits: "5"
          - IndexName: "GSI-3"
            KeySchema:
              - AttributeName: "PK3"
                KeyType: "HASH"
              - AttributeName: "SK3"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: "5"
              WriteCapacityUnits: "5"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: !Ref TableWithComplexBeaconIndexName

  # This policy SHOULD be given to:
  #  - awslabs/aws-dynamodb-encryption-dafny
  #  - ToolsDevelopment
  TestTableUsage:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Allow Read, Write, and Delete of Items in Test Table"
      ManagedPolicyName: !Sub "${ProjectName}-DDB-ReadWriteDelete-${AWS::Region}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}/index/*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableWithSimpleBeaconIndexName}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableWithSimpleBeaconIndexName}/index/*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableWithComplexBeaconIndexName}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableWithComplexBeaconIndexName}/index/*"

  KMSUsage:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "${ProjectName}-KMS-${AWS::Region}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource:
              - !Sub "arn:aws:kms:*:658956600833:key/*"
              - !Sub "arn:aws:kms:*:658956600833:alias/*"

  GitHubCIRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub "GitHub-CI-${ProjectName}-Role-${AWS::Region}"
      Description: "Access DDB, KMS, & CA Resources for CI from GitHub"
      ManagedPolicyArns:
        - Fn::ImportValue: "Polymorph-CA-GitHubCAReadPolicyArn"
        - "arn:aws:iam::370957321024:policy/ESDK-Dafny-DDB-ReadWriteDelete-us-west-2"
        - "arn:aws:iam::370957321024:policy/Hierarchical-GitHub-KMS-Key-Policy"
        - !Ref KMSUsage
        - !Ref TestTableUsage
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",   
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com" },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                  "token.actions.githubusercontent.com:sub": "repo:${GitHubRepo}:*"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::${AWS::AccountId}:role/ToolsDevelopment" },
              "Action": "sts:AssumeRole"
            }
          ]
        }
