// Code generated by smithy-go-codegen DO NOT EDIT.

package WrappedAwsCryptographyDbEncryptionSdkDynamoDbTransformsService

import (
	"context"

	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/AwsCryptographyDbEncryptionSdkDynamoDbTypes"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/awscryptographydbencryptionsdkdynamodbtransformssmithygenerated"
)

type Shim struct {
	AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.IDynamoDbEncryptionTransformsClient
	client *awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Client
}

func (_static *CompanionStruct_Default___) WrappedDynamoDbEncryptionTransforms(inputConfig AwsCryptographyDbEncryptionSdkDynamoDbTypes.DynamoDbTablesEncryptionConfig) Wrappers.Result {
	var nativeConfig = awscryptographydbencryptionsdkdynamodbsmithygenerated.awscryptographydbencryptionsdkdynamodbsmithygenerated.DynamoDbTablesEncryptionConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) PutItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.PutItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.PutItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.PutItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.PutItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) PutItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.PutItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.PutItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.PutItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.PutItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) GetItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.GetItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.GetItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.GetItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.GetItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) GetItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.GetItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.GetItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.GetItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.GetItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchWriteItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchWriteItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchWriteItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchWriteItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchWriteItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchWriteItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchWriteItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchWriteItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchWriteItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchWriteItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchGetItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchGetItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchGetItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchGetItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchGetItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchGetItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchGetItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchGetItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchGetItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchGetItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ScanInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ScanInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ScanInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ScanInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ScanInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ScanOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ScanOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ScanOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ScanOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ScanOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) QueryInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.QueryInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.QueryInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.QueryInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.QueryInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) QueryOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.QueryOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.QueryOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.QueryOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.QueryOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) TransactWriteItemsInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.TransactWriteItemsInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactWriteItemsInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.TransactWriteItemsInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactWriteItemsInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) TransactWriteItemsOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.TransactWriteItemsOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactWriteItemsOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.TransactWriteItemsOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactWriteItemsOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) UpdateItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.UpdateItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.UpdateItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.UpdateItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.UpdateItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) UpdateItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.UpdateItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.UpdateItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.UpdateItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.UpdateItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) DeleteItemInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.DeleteItemInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.DeleteItemInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.DeleteItemInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.DeleteItemInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) DeleteItemOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.DeleteItemOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.DeleteItemOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.DeleteItemOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.DeleteItemOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) TransactGetItemsInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.TransactGetItemsInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactGetItemsInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.TransactGetItemsInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactGetItemsInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) TransactGetItemsOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.TransactGetItemsOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactGetItemsOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.TransactGetItemsOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.TransactGetItemsOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ExecuteStatementInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ExecuteStatementInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteStatementInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ExecuteStatementInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteStatementInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ExecuteStatementOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ExecuteStatementOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteStatementOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ExecuteStatementOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteStatementOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchExecuteStatementInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchExecuteStatementInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchExecuteStatementInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchExecuteStatementInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchExecuteStatementInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) BatchExecuteStatementOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.BatchExecuteStatementOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchExecuteStatementOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.BatchExecuteStatementOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.BatchExecuteStatementOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ExecuteTransactionInputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ExecuteTransactionInputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteTransactionInputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ExecuteTransactionInputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteTransactionInputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ExecuteTransactionOutputTransform(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ExecuteTransactionOutputTransformInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteTransactionOutputTransformInput_FromDafny(input)
	var native_response, native_error = shim.client.ExecuteTransactionOutputTransform(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ExecuteTransactionOutputTransformOutput_ToDafny(*native_response))
}

func (shim *Shim) ResolveAttributes(input AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.ResolveAttributesInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ResolveAttributesInput_FromDafny(input)
	var native_response, native_error = shim.client.ResolveAttributes(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbtransformssmithygenerated.ResolveAttributesOutput_ToDafny(*native_response))
}
