// Class __default
// Dafny class __default compiled into Java
package TransactWriteItemsTransformTest_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static void TestTransactWriteItemsInputPassthrough()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("bar"));
    _1_tableName = _out1;
    dafny.DafnySequence<? extends Character> _2_thisAttr;
    _2_thisAttr = TestFixtures_Compile.__default.GetAttrName(dafny.DafnySequence.asString("this"));
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _3_item;
    _3_item = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Put._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete.create(dafny.DafnyMap.fromElements(new dafny.Tuple2(_2_thisAttr, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("that")))), _1_tableName, Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends Character>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends Character>>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeName._typeDescriptor())), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue>_typeDescriptor(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue._typeDescriptor())), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnValuesOnConditionCheckFailure>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnValuesOnConditionCheckFailure._typeDescriptor()))), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Update>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Update._typeDescriptor()));
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _4_items;
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _out2;
    _out2 = TestFixtures_Compile.__default.GetTransactWriteItemList(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), _3_item));
    _4_items = _out2;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _5_input;
    _5_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_4_items, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ClientRequestToken._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _6_transformed;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out3;
    _out3 = (_0_middlewareUnderTest).TransactWriteItemsInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformInput.create(_5_input));
    _6_transformed = _out3;
    TestFixtures_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>expect__ok(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor(), dafny.DafnySequence.asString("TransactWriteItemsInput"), _6_transformed);
    TestFixtures_Compile.__default.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput>expect__equal(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput._typeDescriptor(), dafny.DafnySequence.asString("TransactWriteItemsInput"), ((_6_transformed).dtor_value()).dtor_transformedInput(), _5_input);
  }
  public static void TestTransactWriteItemsInputEmpty()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _1_item;
    _1_item = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Put._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Update>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Update._typeDescriptor()));
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _2_items;
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _out1;
    _out1 = TestFixtures_Compile.__default.GetTransactWriteItemList(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), _1_item));
    _2_items = _out1;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _3_input;
    _3_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_2_items, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ClientRequestToken._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _4_transformed;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out2;
    _out2 = (_0_middlewareUnderTest).TransactWriteItemsInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformInput.create(_3_input));
    _4_transformed = _out2;
    TestFixtures_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput>ExpectFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsInputTransformOutput._typeDescriptor(), _4_transformed, dafny.DafnySequence.asString("Each item in TransactWriteItems must specify at least one supported operation"));
  }
  public static void TestTransactWriteItemsOutputTransform()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput _1_output;
    _1_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput.create(Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))));
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem _2_item;
    _2_item = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConditionCheck._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Put>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Put._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Delete._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.Update>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.Update._typeDescriptor()));
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _3_items;
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> _out1;
    _out1 = TestFixtures_Compile.__default.GetTransactWriteItemList(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItem._typeDescriptor(), _2_item));
    _3_items = _out1;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput _4_input;
    _4_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsInput.create(_3_items, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ClientRequestToken._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _5_transformed;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out2;
    _out2 = (_0_middlewareUnderTest).TransactWriteItemsOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformInput.create(_1_output, _4_input));
    _5_transformed = _out2;
    TestFixtures_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput>expect__ok(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.TransactWriteItemsOutputTransformOutput._typeDescriptor(), dafny.DafnySequence.asString("TransactWriteItemsOutput"), _5_transformed);
    TestFixtures_Compile.__default.<software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput>expect__equal(software.amazon.cryptography.services.dynamodb.internaldafny.types.TransactWriteItemsOutput._typeDescriptor(), dafny.DafnySequence.asString("TransactWriteItemsOutput"), ((_5_transformed).dtor_value()).dtor_transformedOutput(), _1_output);
  }
  @Override
  public java.lang.String toString() {
    return "TransactWriteItemsTransformTest._default";
  }
}
