// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographymaterialproviderssmithygenerated

import (
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/AwsCryptographyMaterialProvidersTypes"
	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/mpl/awscryptographymaterialproviderssmithygeneratedtypes"
	"github.com/aws/aws-sdk-go-v2/service/kms"
)

type ClientSupplier struct {
	Impl AwsCryptographyMaterialProvidersTypes.IClientSupplier
}

func (this *ClientSupplier) GetClient(params awscryptographymaterialproviderssmithygeneratedtypes.GetClientInput) (kms.Client, error) {
	var dafny_request AwsCryptographyMaterialProvidersTypes.GetClientInput = GetClientInput_ToDafny(params)
	var dafny_response = this.Impl.GetClient(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyMaterialProvidersTypes.Error)
		var defaultVal kms.Client
		return defaultVal, Error_FromDafny(err)
	}
	var native_response = Aws_cryptography_materialProviders_GetClientOutput_client_FromDafny(dafny_response.Dtor_value())
	return *native_response, nil

}
