// Class __default
// Dafny class __default compiled into Java
package BatchWriteItemTransformTest_Compile;

@SuppressWarnings({"unchecked", "deprecation"})
public class __default {
  public __default() {
  }
  public static void TestBatchWriteItemInputTransform()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _1_tableName = _out1;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest _2_request;
    _2_request = software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest._typeDescriptor()));
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> _3_requests;
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> _out2;
    _out2 = TestFixtures_Compile.__default.GetWriteRequests(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), _2_request));
    _3_requests = _out2;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _4_theMap;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out3;
    _out3 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName, _3_requests)));
    _4_theMap = _out3;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _5_input;
    _5_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_4_theMap, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _6_transformed;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformInput.create(_5_input));
    _6_transformed = _out4;
    TestFixtures_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput>expect__ok(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), dafny.DafnySequence.asString("BatchWriteItemInput"), _6_transformed);
    TestFixtures_Compile.__default.<software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput>expect__equal(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput._typeDescriptor(), dafny.DafnySequence.asString("BatchWriteItemInput"), ((_6_transformed).dtor_value()).dtor_transformedInput(), _5_input);
  }
  public static void TestBatchWriteItemOutputTransform()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput _1_output;
    _1_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))), Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())));
    dafny.DafnySequence<? extends Character> _2_tableName;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _2_tableName = _out1;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest _3_request;
    _3_request = software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest._typeDescriptor()));
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> _4_requests;
    dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> _out2;
    _out2 = TestFixtures_Compile.__default.GetWriteRequests(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), _3_request));
    _4_requests = _out2;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _5_theMap;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out3;
    _out3 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_2_tableName, _4_requests)));
    _5_theMap = _out3;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _6_input;
    _6_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_5_theMap, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _7_transformed;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformInput.create(_1_output, _6_input));
    _7_transformed = _out4;
    TestFixtures_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput>expect__ok(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), dafny.DafnySequence.asString("BatchWriteItemOutput"), _7_transformed);
    TestFixtures_Compile.__default.<software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput>expect__equal(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput._typeDescriptor(), dafny.DafnySequence.asString("BatchWriteItemOutput"), ((_7_transformed).dtor_value()).dtor_transformedOutput(), _1_output);
  }
  public static software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest MakePut(dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> item) {
    return software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest.create(Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest._typeDescriptor(), software.amazon.cryptography.services.dynamodb.internaldafny.types.PutRequest.create(item)), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.DeleteRequest._typeDescriptor()));
  }
  public static void TestBatchWriteItemOutputTransformUnprocessed()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _1_tableName = _out1;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _2_theRequests;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out2;
    _out2 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1()), __default.MakePut(__default.Item2()), __default.MakePut(__default.Item3()), __default.MakePut(__default.Item4())))));
    _2_theRequests = _out2;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _3_input;
    _3_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_2_theRequests, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _4_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out3;
    _out3 = (_0_middlewareUnderTest).BatchWriteItemInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformInput.create(_3_input));
    _4_valueOrError0 = _out3;
    if (!(!((_4_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(114,22): " + java.lang.String.valueOf(_4_valueOrError0));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput _5_transInput;
    _5_transInput = (_4_valueOrError0).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _6_unProcessed;
    _6_unProcessed = ((_5_transInput).dtor_transformedInput()).dtor_RequestItems();
    if (!(!(_6_unProcessed).equals((_3_input).dtor_RequestItems()))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(121,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput _7_output;
    _7_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _6_unProcessed), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))), Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _8_valueOrError1 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformInput.create(_7_output, _3_input));
    _8_valueOrError1 = _out4;
    if (!(!((_8_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(126,23): " + java.lang.String.valueOf(_8_valueOrError1));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput _9_transOutput;
    _9_transOutput = (_8_valueOrError1).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    TestFixtures_Compile.__default.<Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>>expect__equal(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor()), dafny.DafnySequence.asString("BatchWriteOutput"), ((_9_transOutput).dtor_transformedOutput()).dtor_UnprocessedItems(), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _2_theRequests));
  }
  public static void TestBatchWriteItemOutputTransformUnprocessed2()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName1;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _1_tableName1 = _out1;
    dafny.DafnySequence<? extends Character> _2_tableName2;
    dafny.DafnySequence<? extends Character> _out2;
    _out2 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("baz"));
    _2_tableName2 = _out2;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _3_theRequests;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out3;
    _out3 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName1, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1()), __default.MakePut(__default.Item2()))), new dafny.Tuple2(_2_tableName2, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item3()), __default.MakePut(__default.Item4())))));
    _3_theRequests = _out3;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _4_input;
    _4_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_3_theRequests, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _5_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformInput.create(_4_input));
    _5_valueOrError0 = _out4;
    if (!(!((_5_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(146,22): " + java.lang.String.valueOf(_5_valueOrError0));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput _6_transInput;
    _6_transInput = (_5_valueOrError0).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _7_unProcessed;
    _7_unProcessed = ((_6_transInput).dtor_transformedInput()).dtor_RequestItems();
    if (!(!(_7_unProcessed).equals((_4_input).dtor_RequestItems()))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(153,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput _8_output;
    _8_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _7_unProcessed), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))), Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _9_valueOrError1 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out5;
    _out5 = (_0_middlewareUnderTest).BatchWriteItemOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformInput.create(_8_output, _4_input));
    _9_valueOrError1 = _out5;
    if (!(!((_9_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(158,23): " + java.lang.String.valueOf(_9_valueOrError1));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput _10_transOutput;
    _10_transOutput = (_9_valueOrError1).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    TestFixtures_Compile.__default.<Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>>expect__equal(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor()), dafny.DafnySequence.asString("BatchWriteOutput"), ((_10_transOutput).dtor_transformedOutput()).dtor_UnprocessedItems(), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _3_theRequests));
  }
  public static void TestBatchWriteItemOutputTransformUnprocessed3()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName1;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _1_tableName1 = _out1;
    dafny.DafnySequence<? extends Character> _2_tableName2;
    dafny.DafnySequence<? extends Character> _out2;
    _out2 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("baz"));
    _2_tableName2 = _out2;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _3_theRequests;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out3;
    _out3 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName1, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1()), __default.MakePut(__default.Item2()))), new dafny.Tuple2(_2_tableName2, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item3()), __default.MakePut(__default.Item4())))));
    _3_theRequests = _out3;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _4_input;
    _4_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_3_theRequests, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _5_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformInput.create(_4_input));
    _5_valueOrError0 = _out4;
    if (!(!((_5_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(178,22): " + java.lang.String.valueOf(_5_valueOrError0));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput _6_transInput;
    _6_transInput = (_5_valueOrError0).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    if (!((((_6_transInput).dtor_transformedInput()).dtor_RequestItems()).<dafny.DafnySequence<? extends Character>>contains(_1_tableName1))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(184,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    if (!((((_6_transInput).dtor_transformedInput()).dtor_RequestItems()).<dafny.DafnySequence<? extends Character>>contains(_2_tableName2))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(185,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _7_list;
    _7_list = dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName1, (((dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>)(java.lang.Object)((((_6_transInput).dtor_transformedInput()).dtor_RequestItems()).get(_1_tableName1)))).subsequence(dafny.Helpers.toInt((java.math.BigInteger.ZERO)), dafny.Helpers.toInt((java.math.BigInteger.ONE)))), new dafny.Tuple2(_2_tableName2, (((dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>)(java.lang.Object)((((_6_transInput).dtor_transformedInput()).dtor_RequestItems()).get(_2_tableName2)))).subsequence(dafny.Helpers.toInt((java.math.BigInteger.ZERO)), dafny.Helpers.toInt((java.math.BigInteger.ONE)))));
    if (!(software.amazon.cryptography.services.dynamodb.internaldafny.types.__default.IsValid__BatchWriteItemRequestMap(_7_list))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(191,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _8_unProcessed;
    _8_unProcessed = _7_list;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _9_orig__list;
    _9_orig__list = dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName1, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1()))), new dafny.Tuple2(_2_tableName2, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item3()))));
    if (!(software.amazon.cryptography.services.dynamodb.internaldafny.types.__default.IsValid__BatchWriteItemRequestMap(_9_orig__list))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(198,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _10_originalUnProcessed;
    _10_originalUnProcessed = _9_orig__list;
    if (!(!(_8_unProcessed).equals((_4_input).dtor_RequestItems()))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(201,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput _11_output;
    _11_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _8_unProcessed), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))), Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _12_valueOrError1 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out5;
    _out5 = (_0_middlewareUnderTest).BatchWriteItemOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformInput.create(_11_output, _4_input));
    _12_valueOrError1 = _out5;
    if (!(!((_12_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(206,23): " + java.lang.String.valueOf(_12_valueOrError1));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput _13_transOutput;
    _13_transOutput = (_12_valueOrError1).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    TestFixtures_Compile.__default.<Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>>expect__equal(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor()), dafny.DafnySequence.asString("BatchWriteOutput"), ((_13_transOutput).dtor_transformedOutput()).dtor_UnprocessedItems(), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _10_originalUnProcessed));
  }
  public static void TestBatchWriteItemOutputTransformUnprocessed4()
  {
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _0_middlewareUnderTest;
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.DynamoDbEncryptionTransformsClient _out0;
    _out0 = TestFixtures_Compile.__default.GetDynamoDbEncryptionTransforms2();
    _0_middlewareUnderTest = _out0;
    dafny.DafnySequence<? extends Character> _1_tableName1;
    dafny.DafnySequence<? extends Character> _out1;
    _out1 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("foo"));
    _1_tableName1 = _out1;
    dafny.DafnySequence<? extends Character> _2_tableName2;
    dafny.DafnySequence<? extends Character> _out2;
    _out2 = TestFixtures_Compile.__default.GetTableName(dafny.DafnySequence.asString("baz"));
    _2_tableName2 = _out2;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _3_theRequests;
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _out3;
    _out3 = TestFixtures_Compile.__default.GetBatchWriteItemRequestMap(dafny.DafnyMap.fromElements(new dafny.Tuple2(_1_tableName1, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1()), __default.MakePut(__default.Item1a()))), new dafny.Tuple2(_2_tableName2, dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest> of(software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest._typeDescriptor(), __default.MakePut(__default.Item1b()), __default.MakePut(__default.Item1c())))));
    _3_theRequests = _out3;
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput _4_input;
    _4_input = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemInput.create(_3_theRequests, Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnConsumedCapacity._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.ReturnItemCollectionMetrics._typeDescriptor()));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _5_valueOrError0 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>)null;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out4;
    _out4 = (_0_middlewareUnderTest).BatchWriteItemInputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformInput.create(_4_input));
    _5_valueOrError0 = _out4;
    if (!(!((_5_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(247,22): " + java.lang.String.valueOf(_5_valueOrError0));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput _6_transInput;
    _6_transInput = (_5_valueOrError0).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemInputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>> _7_unProcessed;
    _7_unProcessed = ((_6_transInput).dtor_transformedInput()).dtor_RequestItems();
    if (!(!(_7_unProcessed).equals((_4_input).dtor_RequestItems()))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(254,4): " + (dafny.DafnySequence.asString("expectation violation")).verbatimString());
    }
    software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput _8_output;
    _8_output = software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemOutput.create(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _7_unProcessed), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>>create_None(dafny.DafnyMap.<dafny.DafnySequence<? extends Character>, dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.TableArn._typeDescriptor(), dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ItemCollectionMetrics._typeDescriptor()))), Wrappers_Compile.Option.<dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>>create_None(dafny.DafnySequence.<software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.ConsumedCapacity._typeDescriptor())));
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _9_valueOrError1 = Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput.Default());
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput, software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error> _out5;
    _out5 = (_0_middlewareUnderTest).BatchWriteItemOutputTransform(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformInput.create(_8_output, _4_input));
    _9_valueOrError1 = _out5;
    if (!(!((_9_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor())))) {
      throw new dafny.DafnyHaltException("dafny/DynamoDbEncryptionTransforms/test/BatchWriteItemTransform.dfy(259,23): " + java.lang.String.valueOf(_9_valueOrError1));
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput _10_transOutput;
    _10_transOutput = (_9_valueOrError1).Extract(software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.BatchWriteItemOutputTransformOutput._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.internaldafny.types.Error._typeDescriptor());
    TestFixtures_Compile.__default.<Wrappers_Compile.Option<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>>expect__equal(Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>_typeDescriptor(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor()), dafny.DafnySequence.asString("BatchWriteOutput"), ((_10_transOutput).dtor_transformedOutput()).dtor_UnprocessedItems(), Wrappers_Compile.Option.<dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends dafny.DafnySequence<? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.WriteRequest>>>create_Some(software.amazon.cryptography.services.dynamodb.internaldafny.types.BatchWriteItemRequestMap._typeDescriptor(), _3_theRequests));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item1()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar1"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign1"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt1"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain1"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item2()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar2"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign2"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt2"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain2"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item3()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar3"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign3"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt3"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain3"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item4()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar4"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign4"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt4"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain4"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item1a()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar1"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign2"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt2"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain2"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item1b()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar1"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign3"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt3"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain3"))));
  }
  public static dafny.DafnyMap<? extends dafny.DafnySequence<? extends Character>, ? extends software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue> Item1c()
  {
    return dafny.DafnyMap.fromElements(new dafny.Tuple2(dafny.DafnySequence.asString("bar"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("bar1"))), new dafny.Tuple2(dafny.DafnySequence.asString("sign"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("sign4"))), new dafny.Tuple2(dafny.DafnySequence.asString("encrypt"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("encrypt4"))), new dafny.Tuple2(dafny.DafnySequence.asString("plain"), software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeValue.create_S(dafny.DafnySequence.asString("plain4"))));
  }
  @Override
  public java.lang.String toString() {
    return "BatchWriteItemTransformTest._default";
  }
}
