// Code generated by smithy-go-codegen DO NOT EDIT.

package WrappedAwsCryptographyDbEncryptionSdkDynamoDbService

import (
	"context"

	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/AwsCryptographyDbEncryptionSdkDynamoDbTypes"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/releases/go/dynamodb-esdk/awscryptographydbencryptionsdkdynamodbsmithygenerated"
)

type Shim struct {
	AwsCryptographyDbEncryptionSdkDynamoDbTypes.IDynamoDbEncryptionClient
	client *awscryptographydbencryptionsdkdynamodbsmithygenerated.Client
}

func (_static *CompanionStruct_Default___) WrappedDynamoDbEncryption(inputConfig AwsCryptographyDbEncryptionSdkDynamoDbTypes.DynamoDbEncryptionConfig) Wrappers.Result {
	var nativeConfig = awscryptographydbencryptionsdkdynamodbsmithygenerated.DynamoDbEncryptionConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = awscryptographydbencryptionsdkdynamodbsmithygenerated.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(AwsCryptographyDbEncryptionSdkDynamoDbTypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) CreateDynamoDbEncryptionBranchKeyIdSupplier(input AwsCryptographyDbEncryptionSdkDynamoDbTypes.CreateDynamoDbEncryptionBranchKeyIdSupplierInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbsmithygenerated.CreateDynamoDbEncryptionBranchKeyIdSupplierInput_FromDafny(input)
	var native_response, native_error = shim.client.CreateDynamoDbEncryptionBranchKeyIdSupplier(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbsmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbsmithygenerated.CreateDynamoDbEncryptionBranchKeyIdSupplierOutput_ToDafny(*native_response))
}

func (shim *Shim) GetEncryptedDataKeyDescription(input AwsCryptographyDbEncryptionSdkDynamoDbTypes.GetEncryptedDataKeyDescriptionInput) Wrappers.Result {
	var native_request = awscryptographydbencryptionsdkdynamodbsmithygenerated.GetEncryptedDataKeyDescriptionInput_FromDafny(input)
	var native_response, native_error = shim.client.GetEncryptedDataKeyDescription(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(awscryptographydbencryptionsdkdynamodbsmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(awscryptographydbencryptionsdkdynamodbsmithygenerated.GetEncryptedDataKeyDescriptionOutput_ToDafny(*native_response))
}
