// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbsmithygeneratedtypes

type LegacyPolicy string

const (
	LegacyPolicyForceLegacyEncryptAllowLegacyDecrypt   LegacyPolicy = "FORCE_LEGACY_ENCRYPT_ALLOW_LEGACY_DECRYPT"
	LegacyPolicyForbidLegacyEncryptAllowLegacyDecrypt  LegacyPolicy = "FORBID_LEGACY_ENCRYPT_ALLOW_LEGACY_DECRYPT"
	LegacyPolicyForbidLegacyEncryptForbidLegacyDecrypt LegacyPolicy = "FORBID_LEGACY_ENCRYPT_FORBID_LEGACY_DECRYPT"
)

func (LegacyPolicy) Values() []LegacyPolicy {
	return []LegacyPolicy{
		"FORCE_LEGACY_ENCRYPT_ALLOW_LEGACY_DECRYPT",
		"FORBID_LEGACY_ENCRYPT_ALLOW_LEGACY_DECRYPT",
		"FORBID_LEGACY_ENCRYPT_FORBID_LEGACY_DECRYPT",
	}
}

type PlaintextOverride string

const (
	PlaintextOverrideForcePlaintextWriteAllowPlaintextRead   PlaintextOverride = "FORCE_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ"
	PlaintextOverrideForbidPlaintextWriteAllowPlaintextRead  PlaintextOverride = "FORBID_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ"
	PlaintextOverrideForbidPlaintextWriteForbidPlaintextRead PlaintextOverride = "FORBID_PLAINTEXT_WRITE_FORBID_PLAINTEXT_READ"
)

func (PlaintextOverride) Values() []PlaintextOverride {
	return []PlaintextOverride{
		"FORCE_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ",
		"FORBID_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ",
		"FORBID_PLAINTEXT_WRITE_FORBID_PLAINTEXT_READ",
	}
}
