// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbsmithygeneratedtypes

import (
	"fmt"
)

type DynamoDbEncryptionException struct {
	DynamoDbEncryptionBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e DynamoDbEncryptionException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
