name: "Check Out and update files with MPL-HEAD"
description: "Updates the MPL submodule to point at HEAD and updates the files that depend on the version defined in project.properties"
inputs:
  dafny:
    description: "The Dafny version to run"
    required: true
    type: string
  update-and-regenerate-mpl:
    description: "Locally update MPL to the tip of master and regenerate its code"
    required: true
    default: false
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Update MPL submodule locally if requested
      if: inputs.update-and-regenerate-mpl == 'true'
      working-directory: submodules/MaterialProviders
      shell: bash
      run: |
        git checkout main
        git pull
        git submodule update --init --recursive

    - name: Get the MPL version from the MPL submodule
      id: read_property
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: "submodules/MaterialProviders/project.properties"
        properties: "mplVersion"

    - name: Update top-level project.properties file
      shell: bash
      run: |
        sed "s/mplDependencyJavaVersion=.*/mplDependencyJavaVersion=${{steps.read_property.outputs.mplVersion}}/g" project.properties > project.properties2; mv project.properties2 project.properties
