$version: "2.0"

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// The single, hand-written source of truth for the TestServer wire contract.
//
// This is PLAIN Smithy 2.0: it uses only standard Smithy constructs and the
// standard RPC v2 CBOR protocol trait. It intentionally does NOT use any
// `aws.polymorph` custom traits, because the TestServer is a standalone
// conformance harness generated by standard Smithy tooling (smithy-java)
// rather than by smithy-dafny/polymorph (Req 2.2).
//
// Protocol: Smithy RPC v2 CBOR (smithy.protocols#rpcv2Cbor). It is supported by
// smithy-java and, unlike restJson1, needs no per-operation HTTP binding traits,
// so the entire transport is described by a single service-level trait. The
// contract is declared once here and applies uniformly to every Language_Server
// (Req 8.1).
namespace aws.cryptography.dbEncryptionSdk.testServer

use smithy.protocols#rpcv2Cbor

/// The TestServer service. Every Language_Server (Java first) implements this
/// exact contract, generated from this one model.
@rpcv2Cbor
service TestServer {
    version: "2024-01-01"
    operations: [
        CreateClient
        WriteItem
        ReadItem
    ]
    // Both modeled errors apply to every operation (Reqs 2.7, 2.8). They are
    // also restated on each operation below to match the design's shape
    // sketches and make the per-operation contract explicit.
    errors: [
        GenericServerError
        DBESDKClientError
    ]
}

// =============================================================================
// CreateClient
// =============================================================================

/// Construct a configured DB-ESDK Enhanced Client from the supplied
/// configuration and return a ClientId bound to it (Reqs 2.3, 4.1).
operation CreateClient {
    input: CreateClientInput
    output: CreateClientOutput
    errors: [
        GenericServerError
        DBESDKClientError
    ]
}

/// Configuration for the Enhanced Client to construct. The per-table
/// configuration mirrors `DynamoDbTableEncryptionConfig` from the DB-ESDK model
/// field-for-field by name and shape (Req 2.5).
structure CreateClientInput {
    @required
    tableEncryptionConfigs: TableEncryptionConfigList
}

structure CreateClientOutput {
    /// A unique, non-empty identifier for the constructed client (Reqs 2.3, 4.1).
    @required
    clientId: ClientId
}

/// A unique identifier for a constructed client. Non-empty by construction
/// (Req 2.3).
@length(min: 1)
string ClientId

// =============================================================================
// WriteItem
// =============================================================================

/// Encrypt and write an item using a previously constructed client (Req 5.1).
operation WriteItem {
    input: WriteItemInput
    output: WriteItemOutput
    errors: [
        GenericServerError
        DBESDKClientError
    ]
}

structure WriteItemInput {
    /// Selects the client constructed by CreateClient. Required on every
    /// non-CreateClient operation (Req 2.4).
    @required
    clientId: ClientId

    /// The physical DynamoDB table to write to.
    @required
    tableName: String

    /// The plaintext item to encrypt and write.
    @required
    item: Item
}

structure WriteItemOutput {
    /// Indicates the write completed successfully (Req 5.1).
    @required
    completed: Boolean
}

// =============================================================================
// ReadItem
// =============================================================================

/// Read and decrypt an item using a previously constructed client (Req 5.2).
operation ReadItem {
    input: ReadItemInput
    output: ReadItemOutput
    errors: [
        GenericServerError
        DBESDKClientError
    ]
}

structure ReadItemInput {
    /// Selects the client constructed by CreateClient (Req 2.4).
    @required
    clientId: ClientId

    /// The physical DynamoDB table to read from.
    @required
    tableName: String

    /// The primary key of the item to read.
    @required
    key: Key
}

structure ReadItemOutput {
    /// False when no item matched the supplied key (Req 5.4).
    @required
    found: Boolean

    /// The decrypted plaintext item. Present only when `found` is true.
    item: Item
}

// =============================================================================
// Enhanced Client configuration shapes (mirror of the DB-ESDK model — Req 2.5)
// =============================================================================

/// Map of physical DynamoDB table name to its encryption configuration.
/// Mirrors `DynamoDbTableEncryptionConfigList`.
map TableEncryptionConfigList {
    key: String
    value: TableEncryptionConfig
}

/// Per-table encryption configuration. Mirrors `DynamoDbTableEncryptionConfig`
/// field-for-field by name and shape for the fields needed to configure an
/// Enhanced Client (Req 2.5). The polymorph `reference` fields (keyring/cmm) of
/// the source model are expressed here as plain structures, since this model
/// uses no `aws.polymorph` traits.
structure TableEncryptionConfig {
    @required
    logicalTableName: String

    @required
    partitionKeyName: String

    sortKeyName: String

    /// Map of attribute name to the action taken for that attribute on encrypt.
    /// Mirrors `AttributeActions`.
    @required
    attributeActionsOnEncrypt: AttributeActions

    /// Attribute names treated as unsigned on decrypt.
    allowedUnsignedAttributes: AttributeNameList

    /// Attribute-name prefix treated as unsigned on decrypt.
    allowedUnsignedAttributePrefix: String

    /// Enum mirror of `DBEAlgorithmSuiteId`.
    algorithmSuiteId: DBEAlgorithmSuiteId

    /// The keyring used to wrap and unwrap data keys (keyring XOR cmm). For the
    /// MVP the materials provider is expressed as a keyring configuration.
    keyring: KeyringConfig

    /// Enum mirror of `PlaintextOverride`.
    plaintextOverride: PlaintextOverride
}

/// Mirrors `AttributeActions`: attribute name -> crypto action.
map AttributeActions {
    key: String
    value: CryptoAction
}

list AttributeNameList {
    member: String
}

/// Enum mirror of the structured-encryption `CryptoAction` enum.
enum CryptoAction {
    ENCRYPT_AND_SIGN
    SIGN_AND_INCLUDE_IN_ENCRYPTION_CONTEXT
    SIGN_ONLY
    DO_NOTHING
}

/// Enum mirror of `DBEAlgorithmSuiteId` (the two DBE-supported suites).
enum DBEAlgorithmSuiteId {
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384_SYMSIG_HMAC_SHA384
    ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_SYMSIG_HMAC_SHA384
}

/// Enum mirror of `PlaintextOverride`.
enum PlaintextOverride {
    FORCE_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ
    FORBID_PLAINTEXT_WRITE_ALLOW_PLAINTEXT_READ
    FORBID_PLAINTEXT_WRITE_FORBID_PLAINTEXT_READ
}

/// A keyring configuration, modeled as a "tagged union via optional members":
/// exactly one member is expected to be set, selecting the kind of keyring to
/// build. The handler validates the exactly-one-set rule and rejects a config
/// (with `DBESDKClientError`) when zero or more than one member is present.
///
/// Plain Smithy 2.0 is used deliberately (no `aws.polymorph` traits) so the
/// shape stays consistent with the rest of this model and generates cleanly via
/// standard smithy-java tooling. A true Smithy `union` is avoided here because
/// the `multi` variant must reference `KeyringConfig` recursively, and the
/// optional-members style keeps that recursion and future extension simple.
structure KeyringConfig {
    /// A Raw AES keyring (symmetric wrapping key supplied directly).
    rawAes: RawAesKeyringConfig

    /// A Raw RSA keyring (asymmetric PEM-encoded key pair supplied directly).
    rawRsa: RawRsaKeyringConfig

    /// An AWS KMS keyring for a single-Region symmetric KMS key.
    awsKms: AwsKmsKeyringConfig

    /// An AWS KMS MRK keyring (single-Region or Multi-Region symmetric key).
    awsKmsMrk: AwsKmsMrkKeyringConfig

    /// An AWS KMS MRK multi-keyring (generator + additional KMS key ids).
    awsKmsMrkMulti: AwsKmsMrkMultiKeyringConfig

    /// A multi-keyring composed of a generator keyring and child keyrings.
    multi: MultiKeyringConfig

    /// An AWS KMS RSA keyring (asymmetric KMS key; public key supplied to encrypt).
    awsKmsRsa: AwsKmsRsaKeyringConfig

    /// An AWS KMS ECDH keyring (KmsPrivateKeyToStaticPublicKey agreement scheme).
    awsKmsEcdh: AwsKmsEcdhKeyringConfig

    /// A Raw ECDH keyring (RawPrivateKeyToStaticPublicKey agreement scheme).
    rawEcdh: RawEcdhKeyringConfig

    /// An AWS KMS Hierarchical keyring (branch keys persisted in a DynamoDB key store).
    hierarchical: HierarchicalKeyringConfig

    /// An AWS KMS Discovery keyring (DECRYPT-ONLY; recognizes the wrapping KMS key).
    awsKmsDiscovery: AwsKmsDiscoveryKeyringConfig

    /// An AWS KMS MRK Discovery keyring (DECRYPT-ONLY; single Region).
    awsKmsMrkDiscovery: AwsKmsMrkDiscoveryKeyringConfig

    /// An AWS KMS Discovery multi-keyring (DECRYPT-ONLY; one child per Region).
    awsKmsDiscoveryMulti: AwsKmsDiscoveryMultiKeyringConfig

    /// An AWS KMS MRK Discovery multi-keyring (DECRYPT-ONLY; one child per Region).
    awsKmsMrkDiscoveryMulti: AwsKmsMrkDiscoveryMultiKeyringConfig
}

/// Configuration for a Raw AES keyring. Mirrors
/// `CreateRawAesKeyringInput` from the Material Providers Library.
structure RawAesKeyringConfig {
    /// A namespace associated with this wrapping key.
    @required
    keyNamespace: String

    /// A name associated with this wrapping key.
    @required
    keyName: String

    /// The raw AES wrapping key bytes (16, 24, or 32 bytes).
    @required
    wrappingKey: Blob

    /// The AES-GCM wrapping algorithm this keyring uses.
    @required
    wrappingAlg: AesWrappingAlg
}

/// Configuration for a Raw RSA keyring. Mirrors
/// `CreateRawRsaKeyringInput` from the Material Providers Library. At least one
/// of `publicKey` / `privateKey` must be supplied; both are required for a
/// round-trip (public to encrypt, private to decrypt).
structure RawRsaKeyringConfig {
    /// A namespace associated with this wrapping key.
    @required
    keyNamespace: String

    /// A name associated with this wrapping key.
    @required
    keyName: String

    /// The RSA padding scheme to use with this keyring.
    @required
    paddingScheme: PaddingScheme

    /// The public RSA key as UTF-8 bytes of a PEM-encoded X.509
    /// SubjectPublicKeyInfo structure. Needed to encrypt.
    publicKey: Blob

    /// The private RSA key as UTF-8 bytes of a PEM-encoded PKCS#8
    /// PrivateKeyInfo structure. Needed to decrypt.
    privateKey: Blob
}

/// Configuration for an AWS KMS keyring (single-Region symmetric key). Mirrors
/// `CreateAwsKmsKeyringInput`; the server supplies the KMS client.
structure AwsKmsKeyringConfig {
    /// The AWS KMS key identifier (key id, alias, or ARN). Should not be an MRK.
    @required
    kmsKeyId: String

    /// Optional grant tokens to use when calling KMS.
    grantTokens: GrantTokenList
}

/// Configuration for an AWS KMS MRK keyring (single-Region or Multi-Region
/// symmetric key). Mirrors `CreateAwsKmsMrkKeyringInput`; the server supplies
/// the KMS client.
structure AwsKmsMrkKeyringConfig {
    /// The AWS KMS key identifier (key id, alias, or ARN).
    @required
    kmsKeyId: String

    /// Optional grant tokens to use when calling KMS.
    grantTokens: GrantTokenList
}

/// Configuration for an AWS KMS MRK multi-keyring. Mirrors
/// `CreateAwsKmsMrkMultiKeyringInput`; the MPL constructs KMS clients itself, so
/// no KMS client is supplied. This is the keyring kind the original single
/// `kmsKeyring` member built, preserved here as one of the variants.
structure AwsKmsMrkMultiKeyringConfig {
    /// The generator KMS key id (key id, alias, or ARN). Optional.
    generator: String

    /// Additional KMS key ids (other than the generator). Optional.
    kmsKeyIds: KmsKeyIdList
}

/// Configuration for an AWS KMS RSA keyring. Mirrors `CreateAwsKmsRsaKeyringInput`;
/// the server supplies the KMS client. The table config must use a non-asymmetric-signing
/// algorithm suite (e.g. ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_SYMSIG_HMAC_SHA384).
structure AwsKmsRsaKeyringConfig {
    /// The ARN of the asymmetric (ENCRYPT_DECRYPT, RSA) AWS KMS key.
    @required
    kmsKeyId: String

    /// The RSA wrapping algorithm to use.
    @required
    encryptionAlgorithm: EncryptionAlgorithmSpec

    /// The public RSA key as UTF-8 bytes of a PEM-encoded X.509 SubjectPublicKeyInfo
    /// structure (as exported from KMS). Needed to encrypt.
    publicKey: Blob
}

/// Configuration for an AWS KMS ECDH keyring using the KmsPrivateKeyToStaticPublicKey
/// agreement scheme. Mirrors `CreateAwsKmsEcdhKeyringInput`; the server supplies the KMS
/// client. Use a non-asymmetric-signing algorithm suite.
structure AwsKmsEcdhKeyringConfig {
    /// The sender's AWS KMS ECC key identifier (ARN), used for KeyAgreement.
    @required
    senderKmsIdentifier: String

    /// The recipient's public key as raw DER-encoded X.509 SubjectPublicKeyInfo bytes.
    @required
    recipientPublicKey: Blob

    /// The named curve on which the sender's and recipient's keys lie.
    @required
    curveSpec: ECDHCurveSpec
}

/// Configuration for a Raw ECDH keyring using the RawPrivateKeyToStaticPublicKey agreement
/// scheme. Mirrors `CreateRawEcdhKeyringInput`. No AWS access needed. Use a
/// non-asymmetric-signing algorithm suite.
structure RawEcdhKeyringConfig {
    /// The sender's static private key as UTF-8 bytes of a PEM-encoded PKCS#8 PrivateKeyInfo.
    @required
    senderStaticPrivateKey: Blob

    /// The recipient's public key as raw DER-encoded X.509 SubjectPublicKeyInfo bytes.
    @required
    recipientPublicKey: Blob

    /// The named curve on which the sender's and recipient's keys lie.
    @required
    curveSpec: ECDHCurveSpec
}

/// Configuration for an AWS KMS Hierarchical keyring. Mirrors
/// `CreateAwsKmsHierarchicalKeyringInput`; the server builds the backing `KeyStore`
/// (DynamoDB + KMS clients for the configured region).
structure HierarchicalKeyringConfig {
    /// The DynamoDB table backing the branch-key store.
    @required
    keyStoreTableName: String

    /// The logical key store name bound to the key store table.
    @required
    logicalKeyStoreName: String

    /// The ARN of the symmetric KMS key that wraps the branch keys.
    @required
    kmsKeyArn: String

    /// The branch key identifier to wrap/unwrap data keys with.
    @required
    branchKeyId: String

    /// How long (seconds) branch-key material may be cached before re-retrieval.
    @required
    ttlSeconds: Long

    /// The local cache entry capacity (optional; MPL default applies when absent).
    cacheEntryCapacity: Integer
}

/// Configuration for an AWS KMS Discovery keyring (DECRYPT-ONLY). Mirrors
/// `CreateAwsKmsDiscoveryKeyringInput`; the server supplies the KMS client. When `accountId`
/// is present a `DiscoveryFilter` restricting to that account and `partition` is applied.
structure AwsKmsDiscoveryKeyringConfig {
    /// An allowed AWS account id for the optional discovery filter.
    accountId: String

    /// The AWS partition for the optional discovery filter (default "aws").
    partition: String
}

/// Configuration for an AWS KMS MRK Discovery keyring (DECRYPT-ONLY, single Region). Mirrors
/// `CreateAwsKmsMrkDiscoveryKeyringInput`; the server supplies the KMS client for `region`.
structure AwsKmsMrkDiscoveryKeyringConfig {
    /// The Region this keyring decrypts in.
    @required
    region: String

    /// An allowed AWS account id for the optional discovery filter.
    accountId: String

    /// The AWS partition for the optional discovery filter (default "aws").
    partition: String
}

/// Configuration for an AWS KMS Discovery multi-keyring (DECRYPT-ONLY). Mirrors
/// `CreateAwsKmsDiscoveryMultiKeyringInput`; the MPL builds KMS clients per Region.
structure AwsKmsDiscoveryMultiKeyringConfig {
    /// The Regions this keyring builds discovery child keyrings for.
    @required
    regions: RegionList

    /// An allowed AWS account id for the optional discovery filter.
    accountId: String

    /// The AWS partition for the optional discovery filter (default "aws").
    partition: String
}

/// Configuration for an AWS KMS MRK Discovery multi-keyring (DECRYPT-ONLY). Mirrors
/// `CreateAwsKmsMrkDiscoveryMultiKeyringInput`; the MPL builds KMS clients per Region.
structure AwsKmsMrkDiscoveryMultiKeyringConfig {
    /// The Regions this keyring builds discovery child keyrings for.
    @required
    regions: RegionList

    /// An allowed AWS account id for the optional discovery filter.
    accountId: String

    /// The AWS partition for the optional discovery filter (default "aws").
    partition: String
}

/// A list of AWS Region names.
list RegionList {
    member: String
}

/// Configuration for a multi-keyring composed of an optional generator keyring
/// and a required (possibly empty) list of child keyrings. Mirrors
/// `CreateMultiKeyringInput`; references `KeyringConfig` recursively so any
/// keyring kind can be a generator or child.
structure MultiKeyringConfig {
    /// The generator keyring configuration (optional). Required to encrypt.
    generator: KeyringConfig

    /// The child keyring configurations. Required (non-null); may be empty.
    @required
    childKeyrings: KeyringConfigList
}

/// A list of keyring configurations (children of a multi-keyring).
list KeyringConfigList {
    member: KeyringConfig
}

/// A list of AWS KMS grant tokens.
list GrantTokenList {
    member: String
}

/// A list of AWS KMS key identifiers.
list KmsKeyIdList {
    member: String
}

/// Enum mirror of the Material Providers `AesWrappingAlg`.
enum AesWrappingAlg {
    ALG_AES128_GCM_IV12_TAG16
    ALG_AES192_GCM_IV12_TAG16
    ALG_AES256_GCM_IV12_TAG16
}

/// Enum mirror of the Material Providers `PaddingScheme`.
enum PaddingScheme {
    PKCS1
    OAEP_SHA1_MGF1
    OAEP_SHA256_MGF1
    OAEP_SHA384_MGF1
    OAEP_SHA512_MGF1
}

/// Enum mirror of `software.amazon.awssdk.services.kms.model.EncryptionAlgorithmSpec`
/// (the RSA wrapping algorithms supported by the AWS KMS RSA keyring).
enum EncryptionAlgorithmSpec {
    RSAES_OAEP_SHA_256
    RSAES_OAEP_SHA_1
}

/// Enum mirror of `software.amazon.cryptography.primitives.model.ECDHCurveSpec`.
enum ECDHCurveSpec {
    ECC_NIST_P256
    ECC_NIST_P384
    ECC_NIST_P521
    SM2
}

// =============================================================================
// Item / Key / AttributeValue shapes
// =============================================================================

/// A DynamoDB item: attribute name -> attribute value.
map Item {
    key: String
    value: AttributeValue
}

/// A DynamoDB primary key: attribute name -> attribute value.
map Key {
    key: String
    value: AttributeValue
}

/// A DynamoDB attribute value. Mirrors the DynamoDB attribute-value types
/// needed for an attribute-for-attribute round-trip (Req 7.3): string, number,
/// binary, bool, null, plus map/list for nesting and the set types.
union AttributeValue {
    /// String value.
    S: String
    /// Number value, carried as a string per DynamoDB convention.
    N: String
    /// Binary value.
    B: Blob
    /// String set.
    SS: StringSet
    /// Number set (numbers carried as strings).
    NS: StringSet
    /// Binary set.
    BS: BlobSet
    /// Nested map of attribute values.
    M: Item
    /// List of attribute values.
    L: AttributeValueList
    /// Null value (always true when present).
    NULL: Boolean
    /// Boolean value.
    BOOL: Boolean
}

list AttributeValueList {
    member: AttributeValue
}

list StringSet {
    member: String
}

list BlobSet {
    member: Blob
}

// =============================================================================
// Structured errors (Reqs 2.7, 2.8)
// =============================================================================

/// Framework/server-side failure originating in the TestServer itself (unknown
/// or empty ClientId, registry storage failure, backend connectivity/timeout,
/// malformed request, unrecognized operation). Follows the DB-ESDK
/// structured-error precedent `@error("client") structure { @required message }`.
@error("client")
structure GenericServerError {
    @required
    message: String
}

/// An exception forwarded from the underlying DB-ESDK Enhanced Client (a
/// CreateClient config rejected by the client, or an encrypt/decrypt failure),
/// so tests can assert on client-thrown errors.
@error("client")
structure DBESDKClientError {
    @required
    message: String
}
