#
# This local action sets up code dependencies
# to run Smithy-Dafny CI in GitHub Actions workflows.
#

name: "Install Smithy-Dafny codegen dependencies"
description: "Install Java package dependencies required to run Smithy-Dafny codegen"
runs:
  using: "composite"
  steps:
    - name: Setup Java 17 for codegen
      uses: actions/setup-java@v5
      with:
        distribution: "corretto"
        java-version: "17"

    - name: Install smithy-dafny-codegen dependencies locally
      shell: bash
      run: |
        make -C submodules/smithy-dafny mvn_local_deploy_polymorph_dependencies

    - name: Setup Python, black, and docformatter for code formatting
      uses: actions/setup-python@v6
      with:
        python-version: 3.11
        architecture: x64
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==25.1
        python -m pip install --upgrade docformatter

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.23"

    - name: Install Go imports
      shell: bash
      run: |
        go install golang.org/x/tools/cmd/goimports@v0.36.0

    # Without this the if-dafny-at-least command includes "Downloading ..." output
    - name: Arbitrary makefile target to force downloading Gradle
      shell: bash
      run: |
        make -C submodules/MaterialProviders/StandardLibrary setup_net
