#
# This local action sets up code dependencies
# to run Smithy-Dafny CI in GitHub Actions workflows.
#

name: "Install Smithy-Dafny codegen dependencies"
description: "Install Java package dependencies required to run Smithy-Dafny codegen"
runs:
  using: "composite"
  steps:
    - name: Setup Java 17 for smithy-dafny
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: 17

    - name: Install smithy-dafny-codegen Rust dependencies locally
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :codegen-client:pTML :codegen-core:pTML :rust-runtime:pTML
        build-root-directory: submodules/smithy-dafny/smithy-dafny-codegen-modules/smithy-rs

    - name: Install smithy-dafny-codegen Python dependencies locally
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :smithy-python-codegen:pTML
        build-root-directory: submodules/smithy-dafny/codegen/smithy-dafny-codegen-modules/smithy-python/codegen

    # Without this the if-dafny-at-least command includes "Downloading ..." output
    - name: Arbitrary makefile target to force downloading Gradle
      shell: bash
      run: |
        make -C DynamoDbEncryption setup_net
