// Class _ExternBase___default
// Dafny class __default compiled into Java
package software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny;

@SuppressWarnings({"unchecked", "deprecation"})
public abstract class _ExternBase___default {
  public _ExternBase___default() {
  }
  public static software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DynamoDbItemEncryptorConfig DefaultDynamoDbItemEncryptorConfig() {
    return software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DynamoDbItemEncryptorConfig.create(dafny.DafnySequence.asString("foo"), dafny.DafnySequence.asString("bar"), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.KeySchemaAttributeName._typeDescriptor()), dafny.DafnyMap.fromElements(), Wrappers_Compile.Option.<dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>>>create_None(software.amazon.cryptography.services.dynamodb.internaldafny.types.AttributeNameList._typeDescriptor()), Wrappers_Compile.Option.<dafny.DafnySequence<? extends Character>>create_None(dafny.DafnySequence.<Character>_typeDescriptor(dafny.TypeDescriptor.CHAR)), Wrappers_Compile.Option.<software.amazon.cryptography.materialproviders.internaldafny.types.DBEAlgorithmSuiteId>create_None(software.amazon.cryptography.materialproviders.internaldafny.types.DBEAlgorithmSuiteId._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>create_None(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring.class))), Wrappers_Compile.Option.<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>create_None(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class))), Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.LegacyOverride>create_None(software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.LegacyOverride._typeDescriptor()), Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.PlaintextOverride>create_None(software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.PlaintextOverride._typeDescriptor()));
  }
  public static boolean UnreservedPrefix(dafny.DafnySequence<? extends Character> attr) {
    return (!((DynamoDbItemEncryptorUtil_Compile.__default.ReservedPrefix()).isPrefixOf(attr))) && (!((StructuredEncryptionUtil_Compile.__default.ReservedCryptoContextPrefixString()).isPrefixOf(attr)));
  }
  public static Wrappers_Compile.Result<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> DynamoDbItemEncryptor(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.DynamoDbItemEncryptorConfig config)
  {
    Wrappers_Compile.Result<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> res = (Wrappers_Compile.Result<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)null;
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _0_valueOrError0 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    _0_valueOrError0 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), (((config).dtor_keyring()).is_None()) || (((config).dtor_cmm()).is_None()), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.asString("Cannot provide both a keyring and a CMM")));
    if ((_0_valueOrError0).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_0_valueOrError0).<DynamoDbItemEncryptorClient>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _1_valueOrError1 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    _1_valueOrError1 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), (((config).dtor_keyring()).is_Some()) || (((config).dtor_cmm()).is_Some()), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.asString("Must provide either a keyring or a CMM")));
    if ((_1_valueOrError1).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_1_valueOrError1).<DynamoDbItemEncryptorClient>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    byte _2_version;
    _2_version = AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.__default.VersionFromActions((config).dtor_attributeActionsOnEncrypt());
    software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction _3_keyAction;
    _3_keyAction = AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.__default.KeyActionFromVersion(_2_version);
    dafny.DafnySequence<? extends Character> _4_keyActionStr;
    _4_keyActionStr = AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.__default.KeyActionStringFromVersion(_2_version);
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _5_valueOrError2 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    _5_valueOrError2 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), (((config).dtor_attributeActionsOnEncrypt()).<dafny.DafnySequence<? extends Character>>contains((config).dtor_partitionKeyName())) && (java.util.Objects.equals(((software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction)(java.lang.Object)(((config).dtor_attributeActionsOnEncrypt()).get((config).dtor_partitionKeyName()))), _3_keyAction)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.asString("Partition key attribute action MUST be "), _4_keyActionStr)));
    if ((_5_valueOrError2).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_5_valueOrError2).<DynamoDbItemEncryptorClient>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    Wrappers_Compile.Outcome<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _6_valueOrError3 = Wrappers_Compile.Outcome.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Default(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    _6_valueOrError3 = Wrappers_Compile.__default.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Need(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), !(((config).dtor_sortKeyName()).is_Some()) || ((((config).dtor_attributeActionsOnEncrypt()).<dafny.DafnySequence<? extends Character>>contains(((config).dtor_sortKeyName()).dtor_value())) && (java.util.Objects.equals(((software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction)(java.lang.Object)(((config).dtor_attributeActionsOnEncrypt()).get(((config).dtor_sortKeyName()).dtor_value()))), _3_keyAction))), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.asString("Sort key attribute action MUST be "), _4_keyActionStr)));
    if ((_6_valueOrError3).IsFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_6_valueOrError3).<DynamoDbItemEncryptorClient>PropagateFailure(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    dafny.DafnySequence<? extends dafny.DafnySequence<? extends Character>> _7_attributeNames;
    _7_attributeNames = SortedSets.__default.<Character>SetToOrderedSequence2(dafny.TypeDescriptor.CHAR, ((config).dtor_attributeActionsOnEncrypt()).keySet(), DynamoDbItemEncryptorUtil_Compile.__default::CharLess);
    java.math.BigInteger _hi0 = java.math.BigInteger.valueOf((_7_attributeNames).length());
    for (java.math.BigInteger _8_i = java.math.BigInteger.ZERO; _8_i.compareTo(_hi0) < 0; _8_i = _8_i.add(java.math.BigInteger.ONE)) {
      dafny.DafnySequence<? extends Character> _9_attributeName;
      _9_attributeName = ((dafny.DafnySequence<? extends Character>)(java.lang.Object)((_7_attributeNames).select(dafny.Helpers.toInt((_8_i)))));
      software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction _10_action;
      _10_action = ((software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.CryptoAction)(java.lang.Object)(((config).dtor_attributeActionsOnEncrypt()).get(_9_attributeName)));
      if (!(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.__default.ForwardCompatibleAttributeAction(_9_attributeName, _10_action, (config).dtor_allowedUnsignedAttributes(), (config).dtor_allowedUnsignedAttributePrefix()))) {
        res = Wrappers_Compile.Result.<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Failure(((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.__default.ExplainNotForwardCompatible(_9_attributeName, _10_action, (config).dtor_allowedUnsignedAttributes(), (config).dtor_allowedUnsignedAttributePrefix())));
        return res;
      }
      if (!(__default.UnreservedPrefix(_9_attributeName))) {
        res = Wrappers_Compile.Result.<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Failure(((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.<Character>concatenate(dafny.DafnySequence.asString("Attribute: "), _9_attributeName), dafny.DafnySequence.asString(" is reserved, and may not be configured."))));
        return res;
      }
    }
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _11_structuredEncryptionRes;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient, software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error> _out0;
    _out0 = software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.__default.StructuredEncryption(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.__default.DefaultStructuredEncryptionConfig());
    _11_structuredEncryptionRes = _out0;
    Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _12_valueOrError4 = (Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)null;
    _12_valueOrError4 = (_11_structuredEncryptionRes).<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient.class)), software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)(_13_e_boxed0) -> {
      software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error _13_e = ((software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.Error)(java.lang.Object)(_13_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkDynamoDb(software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.Error.create_AwsCryptographyDbEncryptionSdkStructuredEncryption(_13_e));
    }));
    if ((_12_valueOrError4).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_12_valueOrError4).<DynamoDbItemEncryptorClient>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.types.IStructuredEncryptionClient _14_structuredEncryptionX;
    _14_structuredEncryptionX = (_12_valueOrError4).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient _15_structuredEncryption;
    _15_structuredEncryption = ((software.amazon.cryptography.dbencryptionsdk.structuredencryption.internaldafny.StructuredEncryptionClient)(java.lang.Object)(_14_structuredEncryptionX));
    software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager _16_cmm = null;
    if (((config).dtor_cmm()).is_Some()) {
      _16_cmm = ((config).dtor_cmm()).dtor_value();
    } else {
      software.amazon.cryptography.materialproviders.internaldafny.types.IKeyring _17_keyring;
      _17_keyring = ((config).dtor_keyring()).dtor_value();
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _18_valueOrError5 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error>)null;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out1;
      _out1 = software.amazon.cryptography.materialproviders.internaldafny.__default.MaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.__default.DefaultMaterialProvidersConfig());
      _18_valueOrError5 = _out1;
      if (!(!((_18_valueOrError5).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor())))) {
        throw new dafny.DafnyHaltException("dafny/DynamoDbItemEncryptor/src/Index.dfy(158,21): " + java.lang.String.valueOf(_18_valueOrError5));
      }
      software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient _19_matProv;
      _19_matProv = (_18_valueOrError5).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor());
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _20_maybeCmm;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out2;
      _out2 = (_19_matProv).CreateDefaultCryptographicMaterialsManager(software.amazon.cryptography.materialproviders.internaldafny.types.CreateDefaultCryptographicMaterialsManagerInput.create(_17_keyring));
      _20_maybeCmm = _out2;
      Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _21_valueOrError6 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)null;
      _21_valueOrError6 = (_20_maybeCmm).<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)(_22_e_boxed0) -> {
        software.amazon.cryptography.materialproviders.internaldafny.types.Error _22_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_22_e_boxed0));
        return software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_22_e);
      }));
      if ((_21_valueOrError6).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
        res = (_21_valueOrError6).<DynamoDbItemEncryptorClient>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
        return res;
      }
      _16_cmm = (_21_valueOrError6).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.types.ICryptographicMaterialsManager.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    }
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _23_maybeCmpClient;
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.materialproviders.internaldafny.types.Error> _out3;
    _out3 = software.amazon.cryptography.materialproviders.internaldafny.__default.MaterialProviders(software.amazon.cryptography.materialproviders.internaldafny.__default.DefaultMaterialProvidersConfig());
    _23_maybeCmpClient = _out3;
    Wrappers_Compile.Result<Wrappers_Compile.Option<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _24_valueOrError7 = Wrappers_Compile.Result.<Wrappers_Compile.Option<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>Default(Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>_typeDescriptor(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.class))), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>Default(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.class))));
    Wrappers_Compile.Result<Wrappers_Compile.Option<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _out4;
    _out4 = software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.Build(config);
    _24_valueOrError7 = _out4;
    if ((_24_valueOrError7).IsFailure(Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>_typeDescriptor(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.class))), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_24_valueOrError7).<DynamoDbItemEncryptorClient>PropagateFailure(Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>_typeDescriptor(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.class))), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    Wrappers_Compile.Option<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride> _25_internalLegacyOverride;
    _25_internalLegacyOverride = (_24_valueOrError7).Extract(Wrappers_Compile.Option.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>_typeDescriptor(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.legacy.InternalLegacyOverride.class))), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> _26_valueOrError8 = (Wrappers_Compile.Result<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)null;
    _26_valueOrError8 = (_23_maybeCmpClient).<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>MapFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.materialproviders.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((java.util.function.Function<software.amazon.cryptography.materialproviders.internaldafny.types.Error, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>)(_27_e_boxed0) -> {
      software.amazon.cryptography.materialproviders.internaldafny.types.Error _27_e = ((software.amazon.cryptography.materialproviders.internaldafny.types.Error)(java.lang.Object)(_27_e_boxed0));
      return software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_AwsCryptographyMaterialProviders(_27_e);
    }));
    if ((_26_valueOrError8).IsFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor())) {
      res = (_26_valueOrError8).<DynamoDbItemEncryptorClient>PropagateFailure(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), ((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)));
      return res;
    }
    software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient _28_cmpClient;
    _28_cmpClient = (_26_valueOrError8).Extract(((dafny.TypeDescriptor<software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.materialproviders.internaldafny.MaterialProvidersClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor());
    if (!(((_25_internalLegacyOverride).is_None()) || (((config).dtor_plaintextOverride()).is_None()))) {
      res = Wrappers_Compile.Result.<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Failure(((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error.create_DynamoDbItemEncryptorException(dafny.DafnySequence.asString("Cannot configure both a plaintext policy and a legacy config.")));
      return res;
    }
    software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.PlaintextOverride _29_plaintextOverride;
    if (((config).dtor_plaintextOverride()).is_Some()) {
      _29_plaintextOverride = ((config).dtor_plaintextOverride()).dtor_value();
    } else {
      _29_plaintextOverride = software.amazon.cryptography.dbencryptionsdk.dynamodb.internaldafny.types.PlaintextOverride.create_FORBID__PLAINTEXT__WRITE__FORBID__PLAINTEXT__READ();
    }
    AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.Config _30_internalConfig;
    _30_internalConfig = AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations_Compile.Config.create(_2_version, _28_cmpClient, (config).dtor_logicalTableName(), (config).dtor_partitionKeyName(), (config).dtor_sortKeyName(), _16_cmm, (config).dtor_attributeActionsOnEncrypt(), (config).dtor_allowedUnsignedAttributes(), (config).dtor_allowedUnsignedAttributePrefix(), (config).dtor_algorithmSuiteId(), _15_structuredEncryption, _29_plaintextOverride, _25_internalLegacyOverride);
    DynamoDbItemEncryptorClient _31_client;
    DynamoDbItemEncryptorClient _nw0 = new DynamoDbItemEncryptorClient();
    _nw0.__ctor(_30_internalConfig);
    _31_client = _nw0;
    res = Wrappers_Compile.Result.<DynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Success(((dafny.TypeDescriptor<DynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(DynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), _31_client);
    return res;
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> CreateSuccessOfClient(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient client) {
    return Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Success(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), client);
  }
  public static Wrappers_Compile.Result<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error> CreateFailureOfError(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error error) {
    return Wrappers_Compile.Result.<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient, software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error>create_Failure(((dafny.TypeDescriptor<software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient>)(java.lang.Object)dafny.TypeDescriptor.reference(software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.IDynamoDbItemEncryptorClient.class)), software.amazon.cryptography.dbencryptionsdk.dynamodb.itemencryptor.internaldafny.types.Error._typeDescriptor(), error);
  }
  @Override
  public java.lang.String toString() {
    return "DynamoDbItemEncryptor._default";
  }
}
