# This workflow performs tests in Java with MPL nightly latest.
name: Library Java Backwards Example Tests

on:
  workflow_call:
    inputs:
      mpl-dafny:
        description: "The Dafny version to compile the MPL with (4.2.0, dafny-nightly, etc..)"
        required: true
        type: string
      mpl-commit:
        description: "The MPL commit to use"
        required: false
        default: "main"
        type: string
      mpl-version:
        description: "The MPL version to use"
        required: true
        type: string
      dbesdk-dafny:
        description: "The Dafny version to compile the DBESDK with (4.2.0, dafny-nightly, etc..)"
        required: true
        type: string

jobs:
  testExamplesJava:
    strategy:
      max-parallel: 1
      matrix:
        java-version: [8, 11, 16, 17]
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-DDBEC-Dafny-Role-us-west-2
          role-session-name: DDBEC-Dafny-Java-Tests

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MPL Dafny
        uses: ./submodules/MaterialProviders/.github/actions/setup_dafny/
        with:
          dafny-version: ${{ inputs.mpl-dafny }}

      - name: Update MPL submodule
        working-directory: submodules/MaterialProviders
        run: |
          git fetch
          git checkout ${{inputs.mpl-commit}}
          git submodule update --init --recursive
          git rev-parse HEAD

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: ${{ matrix.java-version }}

      - name: Build MPL with Dafny ${{inputs.mpl-dafny}}
        working-directory: submodules/MaterialProviders/TestVectorsAwsCryptographicMaterialProviders
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_java CORES=$CORES

      - name: Setup DBESDK Dafny
        uses: ./submodules/MaterialProviders/.github/actions/setup_dafny/
        with:
          dafny-version: ${{ inputs.dbesdk-dafny}}

      - name: Update project.properties if using MPL HEAD
        run: |
          sed "s/mplDependencyJavaVersion=.*/mplDependencyJavaVersion=${{inputs.mpl-version}}/g" project.properties > project.properties2; mv project.properties2 project.properties

      - name: Build implementation
        shell: bash
        working-directory: ./DynamoDbEncryption
        run: |
          make transpile_implementation_java
          make transpile_test_java
          make mvn_local_deploy

      - name: Test Examples
        working-directory: ./Examples
        run: |
          # Run simple examples
          gradle -p runtimes/java/DynamoDbEncryption test 
          # Run migration examples
          gradle -p runtimes/java/Migration/PlaintextToAWSDBE test
          gradle -p runtimes/java/Migration/DDBECToAWSDBE test
