# This workflow performs test vectors in Python with MPL nightly latest.
name: Library Python Test Vectors Backwards Interop Tests

on:
  workflow_call:
    inputs:
      mpl-dafny:
        description: "The Dafny version to compile the MPL with (4.2.0, dafny-nightly, etc..)"
        required: true
        type: string
      mpl-commit:
        description: "The MPL commit to use"
        required: false
        default: "main"
        type: string
      mpl-version:
        description: "The MPL version to use"
        required: true
        type: string
      dbesdk-dafny:
        description: "The Dafny version to compile the DBESDK with (4.2.0, dafny-nightly, etc..)"
        required: true
        type: string

jobs:
  testPython:
    strategy:
      matrix:
        library: [TestVectors]
        python-version: [3.11, 3.12, 3.12]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v4.0.0
        with:
          port: 8000
          cors: "*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-DDBEC-Dafny-Role-us-west-2
          role-session-name: DDBEC-Dafny-Python-Tests

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MPL Dafny
        uses: ./submodules/MaterialProviders/.github/actions/setup_dafny/
        with:
          dafny-version: ${{ inputs.mpl-dafny }}

      - name: Update MPL submodule
        working-directory: submodules/MaterialProviders
        run: |
          git fetch
          git checkout ${{inputs.mpl-commit}}
          git submodule update --init --recursive
          git rev-parse HEAD

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build MPL with Dafny ${{inputs.mpl-dafny}}
        working-directory: submodules/MaterialProviders/TestVectorsAwsCryptographicMaterialProviders
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_python CORES=$CORES

      - name: Setup DBESDK Dafny
        uses: ./submodules/MaterialProviders/.github/actions/setup_dafny/
        with:
          dafny-version: ${{ inputs.dbesdk-dafny}}

      - name: Build DynamoDbEncryption implementation
        shell: bash
        working-directory: DynamoDbEncryption
        run: |
          make transpile_python

      - name: Build TestVectors implementation
        shell: bash
        working-directory: ${{matrix.library}}
        run: |
          make transpile_python

      - name: Test TestVectors
        working-directory: ./TestVectors
        run: |
          make test_python_client_interface
