# This workflow runs every weekday at 16:00 UTC (9AM PDT)
name: Daily CI

on:
  schedule:
    - cron: "00 16 * * 1-5"

jobs:
  getVersion:
    # Don't run the cron builds on forks
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/dafny_version.yaml
  getVerifyVersion:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/dafny_verify_version.yaml
  daily-ci-format:
    needs: getVersion
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_format.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-codegen:
    needs: getVersion
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_codegen.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-verification:
    needs: getVerifyVersion
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: ${{needs.getVerifyVersion.outputs.version}}
  daily-ci-java:
    needs: getVersion
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_java_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-net:
    needs: getVersion
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
