# This workflow runs for every pull request
name: PR CI

on:
  pull_request:

jobs:
  getVersion:
    uses: ./.github/workflows/dafny_version.yml
  getVerifyVersion:
    uses: ./.github/workflows/dafny_verify_version.yml
  pr-ci-format:
    needs: getVersion
    uses: ./.github/workflows/library_format.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-codegen:
    needs: getVersion
    uses: ./.github/workflows/ci_codegen.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-verification:
    needs: getVerifyVersion
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: ${{needs.getVerifyVersion.outputs.version}}
  pr-ci-test-vector-verification:
    needs: getVerifyVersion
    uses: ./.github/workflows/test_vector_verification.yml
    with:
      dafny: ${{needs.getVerifyVersion.outputs.version}}
  pr-ci-java:
    needs: getVersion
    uses: ./.github/workflows/ci_test_java.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-java-test-vectors:
    needs: getVersion
    uses: ./.github/workflows/ci_test_vector_java.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-java-examples:
    needs: getVersion
    uses: ./.github/workflows/ci_examples_java.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-net:
    needs: getVersion
    uses: ./.github/workflows/ci_test_net.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-net-test-vectors:
    needs: getVersion
    uses: ./.github/workflows/ci_test_vector_net.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  pr-ci-net-examples:
    needs: getVersion
    uses: ./.github/workflows/ci_examples_net.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
