// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographydbencryptionsdkdynamodbitemencryptorsmithygenerated

import (
	"context"

	"github.com/aws/aws-database-encryption-sdk-dynamodb/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/DynamoDbItemEncryptor"
	"github.com/aws/aws-database-encryption-sdk-dynamodb/awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes"
)

type Client struct {
	DafnyClient AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.IDynamoDbItemEncryptorClient
}

func NewClient(clientConfig awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.DynamoDbItemEncryptorConfig) (*Client, error) {
	var dafnyConfig = DynamoDbItemEncryptorConfig_ToDafny(clientConfig)
	var dafny_response = DynamoDbItemEncryptor.Companion_Default___.DynamoDbItemEncryptor(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.IDynamoDbItemEncryptorClient)
	client := &Client{dafnyClient}
	return client, nil
}

func (client *Client) EncryptItem(ctx context.Context, params awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.EncryptItemInput) (*awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.EncryptItemOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}

	var dafny_request AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.EncryptItemInput = EncryptItemInput_ToDafny(params)
	var dafny_response = client.DafnyClient.EncryptItem(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = EncryptItemOutput_FromDafny(dafny_response.Dtor_value().(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.EncryptItemOutput))
	return &native_response, nil

}

func (client *Client) DecryptItem(ctx context.Context, params awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.DecryptItemInput) (*awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.DecryptItemOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := awscryptographydbencryptionsdkdynamodbitemencryptorsmithygeneratedtypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}

	var dafny_request AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.DecryptItemInput = DecryptItemInput_ToDafny(params)
	var dafny_response = client.DafnyClient.DecryptItem(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = DecryptItemOutput_FromDafny(dafny_response.Dtor_value().(AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes.DecryptItemOutput))
	return &native_response, nil

}
